// packages/vue/src/components/GridBody.vue
<script setup lang="ts">
import { ref } from "vue";
import type {
  GridCore,
  ColumnDefinition,
  CellPosition,
  CellRange,
  CellValue,
  DragState,
  SlotData,
  FillHandlePosition,
  GridLabels,
  RowId,
  VisibleColumnInfo,
} from "@gp-grid/core";
import {
  isCellSelected,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  buildCellClasses,
  formatLabel,
} from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import { renderEditCell } from "../renderers/editRenderer";
import type { Row, VueCellRenderer, VueEditRenderer } from "../types";

const props = defineProps<{
  rowHeight: number;
  totalHeaderHeight: number;
  contentWidth: number;
  contentHeight: number;
  totalWidth: number;
  rowsWrapperOffset: number;
  activeCell: CellPosition | null;
  selectionRange: CellRange | null;
  editingCell: { row: number; col: number; initialValue: CellValue; editId: number } | null;
  hoverPosition: CellPosition | null;
  error: string | null;
  isLoading: boolean;
  totalRows: number;
  labels: GridLabels;
  slotsArray: SlotData[];
  visibleColumnsWithIndices: VisibleColumnInfo[];
  columnPositions: number[];
  columnWidths: number[];
  fillHandlePosition: FillHandlePosition | null;
  dragState: DragState;
  onScroll: () => void;
  onWheel: (e: WheelEvent, dampening: number) => void;
  wheelDampening: number;
  onCellMouseDown: (rowIndex: number, colIndex: number, e: PointerEvent) => void;
  onCellDoubleClick: (rowIndex: number, colIndex: number) => void;
  onCellMouseEnter: (rowIndex: number, colIndex: number) => void;
  onCellMouseLeave: () => void;
  onFillHandleMouseDown: (e: PointerEvent) => void;
  coreRef: GridCore<Row> | null;
  cellRenderers: Record<string, VueCellRenderer>;
  editRenderers: Record<string, VueEditRenderer>;
  globalCellRenderer?: VueCellRenderer;
  globalEditRenderer?: VueEditRenderer;
}>();

const bodyRef = ref<HTMLDivElement | null>(null);

// Get row classes including highlight classes
const getRowClasses = (slot: { rowIndex: number; rowData: Row | undefined }): string => {
  const highlightRowClasses =
    props.coreRef?.highlight?.computeRowClasses(slot.rowIndex, slot.rowData) ?? [];
  return ["gp-grid-row", ...highlightRowClasses].filter(Boolean).join(" ");
};

// Get cell classes
const getCellClasses = (
  rowIndex: number,
  colIndex: number,
  column: ColumnDefinition,
  rowData: Row | undefined,
  _hoverPosition: CellPosition | null,
): string => {
  const isEditing = isCellEditing(rowIndex, colIndex, props.editingCell);
  const active = isCellActive(rowIndex, colIndex, props.activeCell);
  const selected = isCellSelected(rowIndex, colIndex, props.selectionRange);
  const inFillPreview = isCellInFillPreview(
    rowIndex,
    colIndex,
    props.dragState.dragType === "fill",
    props.dragState.fillSourceRange,
    props.dragState.fillTarget,
  );
  const baseCellClasses = buildCellClasses(active, selected, isEditing, inFillPreview);

  const highlightCellClasses =
    props.coreRef?.highlight?.computeCombinedCellClasses(rowIndex, colIndex, column, rowData) ?? [];

  const isRowDragHandle = column.rowDrag === true;
  // Wrap only affects the default text content, so it is irrelevant (and would
  // clash with the edit input) in edit mode.
  const wrapText = column.wrapText === true && !isEditing;

  return [
    baseCellClasses,
    ...highlightCellClasses,
    isRowDragHandle ? "gp-grid-cell--row-drag-handle" : "",
    wrapText ? "gp-grid-cell--wrap" : "",
  ].filter(Boolean).join(" ");
};

// Read raw values through the core so a record-less (columnar) row renders
// exactly like an object row.
const getRawValue = (rowIndex: number, colIndex: number): CellValue =>
  props.coreRef?.getCellValue(rowIndex, colIndex) ?? null;

const getRowIdAt = (rowIndex: number): RowId | undefined =>
  props.coreRef?.getRowId(rowIndex);

const getFieldValueAt = (rowIndex: number, field: string): CellValue =>
  props.coreRef?.getFieldValue(rowIndex, field) ?? null;

defineExpose({ bodyRef });
</script>

<template>
  <div
    ref="bodyRef"
    style="flex: 1; overflow: auto; position: relative"
    @scroll="props.onScroll"
    @wheel="(e) => props.onWheel(e, props.wheelDampening)"
  >
    <!-- Content sizer - provides scroll range -->
    <div
      :style="{
        width: `${Math.max(props.contentWidth, props.totalWidth)}px`,
        height: `${Math.max(props.contentHeight - props.totalHeaderHeight, 0)}px`,
        position: 'relative',
        minWidth: '100%',
      }"
    >
      <!-- Rows wrapper -->
      <div
        class="gp-grid-rows-wrapper"
        :style="{
          width: `${Math.max(props.contentWidth, props.totalWidth)}px`,
          transform: `translateY(${props.rowsWrapperOffset}px)`,
        }"
      >
        <!-- Row slots -->
        <div
          v-for="slot in props.slotsArray.filter((s) => s.rowIndex >= 0)"
          :key="slot.slotId"
          :class="getRowClasses(slot)"
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            transform: `translateY(${slot.translateY}px)`,
            width: `${Math.max(props.contentWidth, props.totalWidth)}px`,
            height: `${props.rowHeight}px`,
          }"
        >
          <div
            v-for="({ column, originalIndex }, visibleIndex) in props.visibleColumnsWithIndices"
            :key="`${slot.slotId}-${column.colId ?? column.field}`"
            :class="getCellClasses(slot.rowIndex, originalIndex, column, slot.rowData, props.hoverPosition)"
            :data-cell-row="slot.rowIndex"
            :data-cell-col="originalIndex"
            :style="{
              position: 'absolute',
              left: `${props.columnPositions[visibleIndex]}px`,
              top: 0,
              width: `${props.columnWidths[visibleIndex]}px`,
              height: `${props.rowHeight}px`,
            }"
            @pointerdown="(e) => props.onCellMouseDown(slot.rowIndex, originalIndex, e)"
            @dblclick="() => props.onCellDoubleClick(slot.rowIndex, originalIndex)"
            @mouseenter="() => props.onCellMouseEnter(slot.rowIndex, originalIndex)"
            @mouseleave="props.onCellMouseLeave"
          >
            <!-- Edit mode -->
            <template v-if="isCellEditing(slot.rowIndex, originalIndex, props.editingCell) && props.editingCell">
              <component
                :is="renderEditCell({
                  column,
                  rowData: slot.rowData,
                  rawValue: getRawValue(slot.rowIndex, originalIndex),
                  rowId: getRowIdAt(slot.rowIndex),
                  getValue: (field) => getFieldValueAt(slot.rowIndex, field),
                  rowIndex: slot.rowIndex,
                  colIndex: originalIndex,
                  initialValue: props.editingCell.initialValue,
                  editId: props.editingCell.editId,
                  core: props.coreRef,
                  editRenderers: props.editRenderers,
                  globalEditRenderer: props.globalEditRenderer,
                })"
              />
            </template>
            <!-- View mode -->
            <template v-else>
              <component
                :is="renderCell({
                  column,
                  rowData: slot.rowData,
                  rawValue: getRawValue(slot.rowIndex, originalIndex),
                  rowId: getRowIdAt(slot.rowIndex),
                  getValue: (field) => getFieldValueAt(slot.rowIndex, field),
                  rowIndex: slot.rowIndex,
                  colIndex: originalIndex,
                  isActive: isCellActive(slot.rowIndex, originalIndex, props.activeCell),
                  isSelected: isCellSelected(slot.rowIndex, originalIndex, props.selectionRange),
                  isEditing: false,
                  cellRenderers: props.cellRenderers,
                  globalCellRenderer: props.globalCellRenderer,
                })"
              />
            </template>
          </div>
        </div>

        <!-- Fill handle -->
        <div
          v-if="props.fillHandlePosition && !props.editingCell"
          class="gp-grid-fill-handle"
          :style="{
            top: `${props.fillHandlePosition.top}px`,
            left: `${props.fillHandlePosition.left}px`,
          }"
          @pointerdown="props.onFillHandleMouseDown"
        />

        <!-- Row drop indicator -->
        <div
          v-if="props.dragState.dragType === 'row-drag' && props.dragState.rowDrag?.dropTargetIndex !== null"
          class="gp-grid-row-drop-indicator"
          :style="{
            transform: `translateY(${props.dragState.rowDrag!.dropIndicatorY}px)`,
            width: `${Math.max(props.contentWidth, props.totalWidth)}px`,
          }"
        />
      </div>

    </div>

    <!-- Error message -->
    <div v-if="props.error" class="gp-grid-error">
      {{ formatLabel(props.labels.errorPrefix, { message: props.error }) }}
    </div>

    <!-- Empty state -->
    <div
      v-if="!props.isLoading && !props.error && props.totalRows === 0"
      class="gp-grid-empty"
    >
      {{ props.labels.emptyState }}
    </div>
  </div>
</template>

// packages/react/src/components/GridBody.tsx
// packages/react/src/components/GridBody.tsx

import React from "react";
import type {
  GridCore,
  ColumnDefinition,
  CellPosition,
  CellRange,
  CellValue,
  DragState,
  SlotData,
  FillHandlePosition,
  GridLabels,
  VisibleColumnInfo,
} from "@gp-grid/core";
import {
  isCellSelected,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  buildCellClasses,
  formatCellValue,
  formatLabel,
} from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import { renderEditCell } from "../renderers/editRenderer";
import type { ReactCellRenderer, ReactEditRenderer } from "../types";

export interface GridBodyProps<TData = unknown> {
  rowHeight: number;
  totalHeaderHeight: number;
  contentWidth: number;
  contentHeight: number;
  totalWidth: number;
  rowsWrapperOffset: number;
  activeCell: CellPosition | null;
  selectionRange: CellRange | null;
  editingCell: { row: number; col: number; initialValue: CellValue; editId: number } | null;
  error: string | null;
  isLoading: boolean;
  totalRows: number;
  labels: GridLabels;
  slotsArray: SlotData<TData>[];
  visibleColumnsWithIndices: VisibleColumnInfo[];
  columnPositions: number[];
  columnWidths: number[];
  fillHandlePosition: FillHandlePosition | null;
  dragState: DragState;
  onScroll: () => void;
  onCellMouseDown: (rowIndex: number, colIndex: number, e: React.PointerEvent) => void;
  onCellDoubleClick: (rowIndex: number, colIndex: number) => void;
  onCellMouseEnter: (rowIndex: number, colIndex: number) => void;
  onCellMouseLeave: () => void;
  onFillHandleMouseDown: (e: React.PointerEvent) => void;
  coreRef: React.RefObject<GridCore<TData> | null>;
  cellRenderers: Record<string, ReactCellRenderer>;
  editRenderers: Record<string, ReactEditRenderer>;
  globalCellRenderer?: ReactCellRenderer;
  globalEditRenderer?: ReactEditRenderer;
}

const GridBodyInner = <TData = unknown>(
  props: GridBodyProps<TData>,
  ref: React.ForwardedRef<HTMLDivElement>,
): React.ReactNode => {
  const {
    rowHeight,
    totalHeaderHeight,
    contentWidth,
    contentHeight,
    totalWidth,
    rowsWrapperOffset,
    activeCell,
    selectionRange,
    editingCell,
    error,
    isLoading,
    totalRows,
    labels,
    slotsArray,
    visibleColumnsWithIndices,
    columnPositions,
    columnWidths,
    fillHandlePosition,
    dragState,
    onScroll,
    onCellMouseDown,
    onCellDoubleClick,
    onCellMouseEnter,
    onCellMouseLeave,
    onFillHandleMouseDown,
    coreRef,
    cellRenderers,
    editRenderers,
    globalCellRenderer,
    globalEditRenderer,
  } = props;

  return (
    <div
      ref={ref}
      style={{
        flex: 1,
        overflow: "auto",
        position: "relative",
      }}
      onScroll={onScroll}
    >
      {/* Content sizer - provides scroll range */}
      <div
        style={{
          width: Math.max(contentWidth, totalWidth),
          height: Math.max(contentHeight - totalHeaderHeight, 0),
          position: "relative",
          minWidth: "100%",
        }}
      >
        {/* Rows wrapper - uses transform to position rows with small translateY values */}
        {/* This prevents browser rendering issues at extreme pixel positions (millions of px) */}
        <div
          className="gp-grid-rows-wrapper"
          style={{
            width: `${Math.max(contentWidth, totalWidth)}px`,
            transform: `translateY(${rowsWrapperOffset}px)`,
          }}
        >
          {/* Row slots */}
          {slotsArray.map((slot) => {
            if (slot.rowIndex < 0) return null;

            const core = coreRef.current;

            // Compute row highlight classes (pass rowData for content-based rules)
            const highlightRowClasses =
              coreRef.current?.highlight?.computeRowClasses(slot.rowIndex, slot.rowData) ?? [];
            const rowClassName = ["gp-grid-row", ...highlightRowClasses]
              .filter(Boolean)
              .join(" ");

            return (
              <div
                key={slot.slotId}
                className={rowClassName}
                style={{
                  position: "absolute",
                  top: 0,
                  left: 0,
                  transform: `translateY(${slot.translateY}px)`,
                  width: `${Math.max(contentWidth, totalWidth)}px`,
                  height: `${rowHeight}px`,
                }}
              >
                {visibleColumnsWithIndices.map(({ column, originalIndex }, visibleIndex) => {
                  const isEditing = isCellEditing(
                    slot.rowIndex,
                    originalIndex,
                    editingCell,
                  );
                  const active = isCellActive(
                    slot.rowIndex,
                    originalIndex,
                    activeCell,
                  );
                  const selected = isCellSelected(
                    slot.rowIndex,
                    originalIndex,
                    selectionRange,
                  );
                  const inFillPreview = isCellInFillPreview(
                    slot.rowIndex,
                    originalIndex,
                    dragState.dragType === "fill",
                    dragState.fillSourceRange,
                    dragState.fillTarget,
                  );

                  // Build base cell classes
                  const baseCellClasses = buildCellClasses(
                    active,
                    selected,
                    isEditing,
                    inFillPreview,
                  );

                  // Compute highlight cell classes
                  const highlightCellClasses =
                    coreRef.current?.highlight?.computeCombinedCellClasses(
                      slot.rowIndex,
                      originalIndex,
                      column,
                      slot.rowData,
                    ) ?? [];

                  // Read the raw value through the core read path so a
                  // record-less (columnar) row renders like an object row.
                  const rawValue =
                    core?.getCellValue(slot.rowIndex, originalIndex) ?? null;
                  const rowId = core?.getRowId(slot.rowIndex);
                  const getValue = (field: string): CellValue =>
                    core?.getFieldValue(slot.rowIndex, field) ?? null;

                  const isRowDragHandle = column.rowDrag === true;
                  // Wrap only affects the default text content, so it is
                  // irrelevant (and would clash with the edit input) in edit mode.
                  const wrapText = column.wrapText === true && !isEditing;

                  const cellClasses = [
                    baseCellClasses,
                    ...highlightCellClasses,
                    isRowDragHandle ? "gp-grid-cell--row-drag-handle" : "",
                    wrapText ? "gp-grid-cell--wrap" : "",
                  ]
                    .filter(Boolean)
                    .join(" ");

                  // Native tooltip: show the formatted value on hover so users
                  // can read content that's clipped by the cell width. Opt out
                  // per column with `tooltip: false`. Suppressed while editing
                  // (the input is focused and has its own value).
                  const titleText =
                    column.tooltip === false || isEditing
                      ? ""
                      : formatCellValue(rawValue, column.valueFormatter);

                  return (
                    <div
                      key={`${slot.slotId}-${originalIndex}`}
                      className={cellClasses}
                      data-cell-row={slot.rowIndex}
                      data-cell-col={originalIndex}
                      title={titleText || undefined}
                      style={{
                        position: "absolute",
                        left: `${columnPositions[visibleIndex]}px`,
                        top: 0,
                        width: `${columnWidths[visibleIndex]}px`,
                        height: `${rowHeight}px`,
                      }}
                      onPointerDown={(e) =>
                        onCellMouseDown(slot.rowIndex, originalIndex, e)
                      }
                      onDoubleClick={() =>
                        onCellDoubleClick(slot.rowIndex, originalIndex)
                      }
                      onMouseEnter={() =>
                        onCellMouseEnter(slot.rowIndex, originalIndex)
                      }
                      onMouseLeave={onCellMouseLeave}
                    >
                      {isEditing && editingCell
                        ? renderEditCell({
                          column,
                          rowData: slot.rowData,
                          rawValue,
                          rowId,
                          getValue,
                          rowIndex: slot.rowIndex,
                          colIndex: originalIndex,
                          initialValue: editingCell.initialValue,
                          editId: editingCell.editId,
                          coreRef,
                          editRenderers,
                          globalEditRenderer,
                        })
                        : renderCell({
                          column,
                          rowData: slot.rowData,
                          rawValue,
                          rowId,
                          getValue,
                          rowIndex: slot.rowIndex,
                          colIndex: originalIndex,
                          isActive: active,
                          isSelected: selected,
                          isEditing,
                          cellRenderers,
                          globalCellRenderer,
                        })}
                    </div>
                  );
                })}
              </div>
            );
          })}

          {/* Fill handle (drag to fill) - inside wrapper so it moves with rows */}
          {fillHandlePosition && !editingCell && (
            <div
              className="gp-grid-fill-handle"
              style={{
                top: fillHandlePosition.top,
                left: fillHandlePosition.left,
              }}
              onPointerDown={onFillHandleMouseDown}
            />
          )}

          {/* Row drop indicator - inside wrapper so it scrolls with rows */}
          {dragState.dragType === "row-drag" && dragState.rowDrag?.dropTargetIndex !== null && (
            <div
              className="gp-grid-row-drop-indicator"
              style={{
                transform: `translateY(${dragState.rowDrag!.dropIndicatorY}px)`,
                width: `${Math.max(contentWidth, totalWidth)}px`,
              }}
            />
          )}
        </div>

      </div>

      {/* Error message */}
      {error && (
        <div className="gp-grid-error">{formatLabel(labels.errorPrefix, { message: error })}</div>
      )}

      {/* Empty state */}
      {!isLoading && !error && totalRows === 0 && (
        <div className="gp-grid-empty">{labels.emptyState}</div>
      )}
    </div>
  );
};

export const GridBody = React.forwardRef(GridBodyInner) as <TData = unknown>(
  props: GridBodyProps<TData> & { ref?: React.Ref<HTMLDivElement> },
) => React.ReactNode;
