// packages/vue/src/components/GridFrozenRows.vue
<script setup lang="ts">
import { computed } from "vue";
import type {
  ColumnRegion,
  ColumnWindowSnapshot,
  FillHandlePosition,
  ResolvedColumn,
  RowRegionLayout,
  SlotData,
} from "@gp-grid/core";
import GridCell from "./GridCell.vue";
import GridRow from "./GridRow.vue";
import type { GridRowCellContext } from "./cell-props";
import { groupDepthStyle } from "./row-group-attributes";
import type { Row } from "../types";

const CENTER_REGIONS: readonly ColumnRegion[] = ["center"];

const props = defineProps<{
  rowRegions: RowRegionLayout;
  /** Frozen slots only; the suffix rows stay in the scrolling wrapper. */
  slots: SlotData<Row>[];
  /** ARIA rows the header takes ahead of the body: its band count. */
  headerRowCount: number;
  columnWindow: ColumnWindowSnapshot | null;
  /** 0-based displayed index of a column id, for `aria-colindex`. */
  displayedIndexOf: (columnId: string) => number;
  contentWidthPx: number;
  cellContext: GridRowCellContext;
  /** Frozen-branch handle; `null` when it is hidden or belongs to the suffix. */
  fillHandlePosition: FillHandlePosition | null;
  /** Frozen-branch row drop indicator, placed in the block's inner wrapper. */
  showDropIndicator: boolean;
}>();

const blockWidth = computed(() => `${props.contentWidthPx}px`);

/** A loading placeholder renders no cells, so it has no pin row either. */
const pinRows = computed(() => props.slots.filter((slot) => slot.loading === false));

const startPinColumns = computed(() => props.columnWindow?.start ?? []);
const endPinColumns = computed(() => props.columnWindow?.end ?? []);
const startPinWidth = computed(() => props.columnWindow?.layout.regions.startWidth ?? 0);
const endPinWidth = computed(() => props.columnWindow?.layout.regions.endWidth ?? 0);

/** Zero-height sticky overlay hosting the handle, so it follows its pin region. */
const pinOverlayWidth = (region: "start" | "end"): number | null => {
  if (props.columnWindow === null || props.fillHandlePosition?.region !== region) return null;
  return region === "start" ? startPinWidth.value : endPinWidth.value;
};

const startOverlayWidth = computed(() => pinOverlayWidth("start"));
const endOverlayWidth = computed(() => pinOverlayWidth("end"));

const pinRowStyle = (slot: SlotData<Row>): string =>
  `position: absolute; top: 0; inset-inline-start: 0; transform: translateY(${slot.translateY}px); width: ${props.contentWidthPx}px; height: ${slot.height}px; display: flex;${groupDepthStyle(slot.row)}`;

const cellProps = (slot: SlotData<Row>, column: ResolvedColumn) => ({
  ...props.cellContext,
  rowIndex: slot.rowIndex,
  rowData: slot.rowData,
  row: slot.row,
  rowHeight: slot.height,
  generation: slot.generation,
  column,
  displayedIndex: props.displayedIndexOf(column.columnId),
});
</script>

<template>
  <template v-if="props.rowRegions.frozenCount > 0">
    <div
      class="gp-grid-frozen-rows"
      role="presentation"
      :style="{ height: `${props.rowRegions.frozenExtent}px`, width: blockWidth }"
    >
      <div
        class="gp-grid-rows-wrapper"
        role="presentation"
        :style="{ width: blockWidth, transform: 'translateY(0)' }"
      >
        <template v-if="props.columnWindow">
          <GridRow
            v-for="slot in props.slots"
            :key="slot.slotId"
            :slot="slot"
            :header-row-count="props.headerRowCount"
            :column-window="props.columnWindow"
            :displayed-index-of="props.displayedIndexOf"
            :width="props.contentWidthPx"
            :cell-context="props.cellContext"
            :regions="CENTER_REGIONS"
          />
        </template>

        <template v-if="props.fillHandlePosition?.region === 'center'">
          <slot name="fill-handle" />
        </template>

        <template v-if="props.showDropIndicator">
          <slot name="drop-indicator" />
        </template>
      </div>
    </div>

    <div
      class="gp-grid-frozen-pins"
      role="presentation"
      :style="{ marginTop: `${-props.rowRegions.frozenExtent}px` }"
    >
      <template v-if="props.columnWindow">
        <div
          v-for="slot in pinRows"
          :key="slot.slotId"
          class="gp-grid-frozen-pin-row"
          role="presentation"
          :data-row-kind="slot.row?.kind"
          :style="pinRowStyle(slot)"
        >
          <div
            v-if="startPinColumns.length > 0"
            class="gp-grid-pin gp-grid-pin--start"
            role="presentation"
            data-pin-region="start"
            :style="{ width: `${startPinWidth}px` }"
          >
            <GridCell
              v-for="column in startPinColumns"
              :key="column.columnId"
              v-bind="cellProps(slot, column)"
            />
          </div>

          <div
            v-if="endPinColumns.length > 0"
            class="gp-grid-pin gp-grid-pin--end"
            role="presentation"
            data-pin-region="end"
            :style="{ width: `${endPinWidth}px` }"
          >
            <GridCell
              v-for="column in endPinColumns"
              :key="column.columnId"
              v-bind="cellProps(slot, column)"
            />
          </div>
        </div>
      </template>

      <div
        v-if="startOverlayWidth !== null"
        class="gp-grid-pin-overlay gp-grid-pin-overlay--start"
        role="presentation"
        :style="{ width: `${startOverlayWidth}px` }"
      >
        <slot name="fill-handle" />
      </div>

      <div
        v-if="endOverlayWidth !== null"
        class="gp-grid-pin-overlay gp-grid-pin-overlay--end"
        role="presentation"
        :style="{ width: `${endOverlayWidth}px` }"
      >
        <slot name="fill-handle" />
      </div>
    </div>
  </template>
</template>

// packages/react/src/components/GridFrozenRows.tsx
// packages/react/src/components/GridFrozenRows.tsx

import React from "react";
import type {
  ColumnRegion,
  ColumnWindowSnapshot,
  FillHandlePosition,
  RowRegionLayout,
  SlotData,
} from "@gp-grid/core";
import { GridRow, GridRowPins, rowBoxStyle } from "./GridRow";
import type { GridRowCellContext } from "./GridRow";
import { groupDepthStyle } from "./row-group-attributes";

const CENTER_REGION: readonly ColumnRegion[] = ["center"];

export interface GridFrozenRowsProps<TData = unknown> {
  rowRegions: RowRegionLayout;
  /** Frozen slots only; the suffix rows stay in the scrolling wrapper. */
  slots: SlotData<TData>[];
  /** ARIA rows the header takes ahead of the body: its band count. */
  headerRowCount: number;
  columnWindow: ColumnWindowSnapshot | null;
  /** 0-based displayed index of a column id, for `aria-colindex`. */
  displayedIndexOf: (columnId: string) => number;
  contentWidthPx: number;
  cellContext: GridRowCellContext<TData>;
  fillHandlePosition: FillHandlePosition | null;
  /** Handle overlay node, placed by row region and column region. */
  fillHandle: React.ReactNode;
  /** Row drop indicator node, placed by row region. */
  dropIndicator: React.ReactNode;
}

/**
 * C10 frozen band: center cells in the sticky block, pinned cells in a sibling
 * sticky layer. The block scrolls horizontally, so a pin inside it would ride
 * its content box out of the viewport (Slice 1 findings).
 */
export const GridFrozenRows = <TData = unknown>(
  props: GridFrozenRowsProps<TData>,
): React.ReactNode => {
  const {
    rowRegions,
    slots,
    headerRowCount,
    columnWindow,
    displayedIndexOf,
    contentWidthPx,
    cellContext,
    fillHandlePosition,
    fillHandle,
    dropIndicator,
  } = props;

  if (rowRegions.frozenCount === 0) return null;

  const blockWidth = `${contentWidthPx}px`;
  const frozenHandle = fillHandlePosition?.rowRegion === "frozen" ? fillHandle : null;
  const centerHandle = fillHandlePosition?.region === "center" ? frozenHandle : null;

  const pinOverlay = (region: "start" | "end"): React.ReactNode => {
    const layout = columnWindow?.layout.regions;
    const hostsHandle =
      frozenHandle !== null && fillHandlePosition?.region === region && layout !== undefined;
    if (hostsHandle === false) return null;
    const width = region === "start" ? layout.startWidth : layout.endWidth;
    return (
      <div
        className={`gp-grid-pin-overlay gp-grid-pin-overlay--${region}`}
        role="presentation"
        style={{ width: `${width}px` }}
      >
        {frozenHandle}
      </div>
    );
  };

  const rows =
    columnWindow === null
      ? null
      : slots.map((slot) => (
        <GridRow
          key={slot.slotId}
          slot={slot}
          headerRowCount={headerRowCount}
          columnWindow={columnWindow}
          displayedIndexOf={displayedIndexOf}
          width={contentWidthPx}
          cellContext={cellContext}
          regions={CENTER_REGION}
        />
      ));

  // A loading placeholder renders no cells, so it has no pin row either.
  const pinRows =
    columnWindow === null
      ? null
      : slots
        .filter((slot) => slot.loading === false)
        .map((slot) => (
          <div
            key={slot.slotId}
            className="gp-grid-frozen-pin-row"
            role="presentation"
            data-row-kind={slot.row?.kind}
            style={{
              ...rowBoxStyle(slot.translateY, contentWidthPx, slot.height),
              ...groupDepthStyle(slot.row),
            }}
          >
            <GridRowPins
              slot={slot}
              columnWindow={columnWindow}
              displayedIndexOf={displayedIndexOf}
              cellContext={cellContext}
            />
          </div>
        ));

  return (
    <>
      <div
        className="gp-grid-frozen-rows"
        role="presentation"
        style={{ height: `${rowRegions.frozenExtent}px`, width: blockWidth }}
      >
        <div
          className="gp-grid-rows-wrapper"
          role="presentation"
          style={{ width: blockWidth, transform: "translateY(0)" }}
        >
          {rows}
          {centerHandle}
          {dropIndicator}
        </div>
      </div>

      <div
        className="gp-grid-frozen-pins"
        role="presentation"
        style={{ marginTop: `${-rowRegions.frozenExtent}px` }}
      >
        {pinRows}
        {pinOverlay("start")}
        {pinOverlay("end")}
      </div>
    </>
  );
};
