// playgrounds/angular/src/app/app.ts
import { Component, signal, effect, PLATFORM_ID, ViewChild, AfterViewInit, ChangeDetectorRef, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { isPlatformBrowser } from '@angular/common';
import { GpGridComponent, provideGridData, injectGridData } from '@gp-grid/angular';
import type {
  AngularColumnDefinition,
  CellRendererTemplate,
  EditRendererParams,
  EditRendererTemplate,
  GridLabels,
  HeaderRendererTemplate,
  HighlightingOptions,
} from '@gp-grid/angular';

interface Person {
  id: number;
  name: string;
  age: number;
  city: string;
  bio: string;
  createdAt: Date;
}

const NAMES = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry'];
const CITIES = ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Rome', 'Sydney', 'Toronto'];

// Long bio strings pooled so the 1.5M-row dataset doesn't allocate millions of
// distinct strings. Each row references one of these by index modulo.
const BIOS: string[] = [
  "Seasoned backend engineer who spent the last decade chasing tail-latency outliers across distributed message brokers. Mentors junior engineers, writes too many internal docs, and is on a quiet mission to retire every YAML file in the company.",
  "Joined fresh out of a bootcamp three years ago and now leads the design system working group. Holds strong opinions about color tokens, accessible focus rings, and the perfect motion duration (always 180ms, never 200).",
  "Former data scientist turned product manager. Still keeps a Jupyter notebook open on the side. Argues that every roadmap should start with a histogram and end with a follow-up question.",
  "Lives in three time zones and is somehow always the first to reply on Slack. Hobbies include long walks, longer postmortems, and convincing reviewers that this PR is, in fact, small.",
  "Joined for the coffee, stayed for the codebase. Has opinions on monorepos, file organization, and whether `index.ts` should be allowed to re-export anything at all (it should not).",
  "Quietly rewrote the deployment pipeline over a long weekend and never told anyone — found out three months later when the on-call rotation noticed the alert volume had dropped by 80%.",
];

// Date pool: small set of timestamps reused across rows to keep memory flat.
const DATES: Date[] = Array.from(
  { length: 60 },
  (_, i) => new Date(Date.now() - i * 86400000 * 5),
);

const generateRows = (count: number): Person[] =>
  Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    name: NAMES[i % NAMES.length],
    age: 20 + (i % 50),
    city: CITIES[i % CITIES.length],
    bio: BIOS[i % BIOS.length],
    createdAt: DATES[i % DATES.length],
  }));

@Component({
  selector: 'app-root',
  imports: [GpGridComponent, FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css',
  providers: [
    provideGridData<Person>({
      getRowId: (row) => row.id,
      initialData: generateRows(1_500_000),
    }),
  ],
})
export class App implements AfterViewInit {
  protected darkMode = signal(false);

  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  private readonly cdr = inject(ChangeDetectorRef);

  @ViewChild('ageBadge', { static: true }) ageBadge!: CellRendererTemplate;
  @ViewChild('cityHeader', { static: true }) cityHeader!: HeaderRendererTemplate;
  @ViewChild('cityEditor', { static: true }) cityEditor!: EditRendererTemplate;

  protected readonly cityOptions = CITIES;

  protected readonly grid = injectGridData<Person>();

  protected rowIdToUpdate = signal(1);

  columns: AngularColumnDefinition[] = [];

  highlighting: HighlightingOptions = {
    computeRowClasses: (ctx) => (ctx.isHovered ? ['pg-row--hover'] : []),
    computeColumnClasses: (ctx) => (ctx.isHovered ? ['pg-col--hover'] : []),
  };

  // Localized labels demo — override only what you need; the rest fall back to
  // the English defaults.
  gridLabels: Partial<GridLabels> = {
    and: 'E',
    filterTitle: 'Filtra: {column}',
    apply: 'Applica',
  };

  constructor() {
    effect(() => {
      if (!this.isBrowser) return;
      document.documentElement.classList.toggle('dark', this.darkMode());
    });
  }

  ngAfterViewInit(): void {
    this.columns = [
      { field: 'id', cellDataType: 'number', headerName: 'ID', width: 80, sortable: true },
      { field: 'name', cellDataType: 'text', headerName: 'Name', width: 200, sortable: true, filterable: true, editable: true },
      { field: 'age', cellDataType: 'number', headerName: 'Age', width: 100, sortable: true, filterable: true, cellRenderer: this.ageBadge },
      { field: 'city', cellDataType: 'text', headerName: 'City', width: 150, sortable: true, filterable: true, editable: true, headerRenderer: this.cityHeader, editRenderer: this.cityEditor, valueFormatter: (v) => `🏙 ${String(v ?? "")}` },
      // Long text column — wrapText lets it flow onto new lines (clipped to the
      // fixed row height) instead of truncating with an ellipsis. Not editable so
      // double-click opens the read-only peek overlay (once the Angular wrapper
      // renders one — currently behaviour-only).
      { field: 'bio', cellDataType: 'text', headerName: 'Bio', width: 260, sortable: true, filterable: true, distinctValues: BIOS, wrapText: true },
      { field: 'createdAt', cellDataType: 'dateTime', headerName: 'Created', width: 200, sortable: true, filterable: true, valueFormatter: (v) => (v instanceof Date ? v.toLocaleString() : '') },
    ];
    this.cdr.detectChanges();
  }

  protected ageTone(value: number): string {
    if (value < 30) return 'young';
    if (value < 50) return 'mid';
    return 'senior';
  }

  protected onCityEditChange(event: Event, params: EditRendererParams): void {
    const value = (event.target as HTMLSelectElement).value;
    params.onValueChange(value);
    params.onCommit();
  }

  protected onCityEditKeyDown(event: KeyboardEvent, params: EditRendererParams): void {
    event.stopPropagation();
    if (event.key === 'Escape') {
      params.onCancel();
    } else if (event.key === 'Enter') {
      params.onCommit();
    }
  }

  protected onRowDragEnd(event: { source: number; target: number }): void {
    console.log(`Row drag: ${event.source} → ${event.target}`);
  }

  protected updateRowRandom(): void {
    this.grid.updateRow(this.rowIdToUpdate(), {
      name: `Person ${NAMES[Math.floor(Math.random() * NAMES.length)]}`,
      age: 20 + Math.floor(Math.random() * 60),
      city: this.cityOptions[Math.floor(Math.random() * this.cityOptions.length)],
    });
  }

  protected toggleDarkMode(): void {
    this.darkMode.update(v => !v);
  }
}

// playgrounds/vite-vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import {
    GpGrid,
    useGridData,
    type ColumnDefinition,
    type HighlightingOptions,
    type GridLabels,
} from "@gp-grid/vue";
import Currency from "./renderers/Currency.vue";
import StatusBadge from "./renderers/StatusBadge.vue";
import Bold from "./renderers/Bold.vue";
import Tags from "./renderers/Tags.vue";
import AgeBucket from "./renderers/AgeBucket.vue";
type HighlightMode = "row" | "column" | "cell";
const highlightMode = ref<HighlightMode>("row");

// Types
interface Person {
    id: number;
    name: string;
    age: number;
    bio: string;
    createdAt: Date;
    status: "active" | "inactive" | "pending";
    salary: number;
    tags: string[];
}

// Long bio strings pooled so the 1.5M-row dataset doesn't allocate millions of
// distinct strings. Each row references one of these by index modulo.
const bioPool: string[] = [
    "Seasoned backend engineer who spent the last decade chasing tail-latency outliers across distributed message brokers. Mentors junior engineers, writes too many internal docs, and is on a quiet mission to retire every YAML file in the company.",
    "Joined fresh out of a bootcamp three years ago and now leads the design system working group. Holds strong opinions about color tokens, accessible focus rings, and the perfect motion duration (always 180ms, never 200).",
    "Former data scientist turned product manager. Still keeps a Jupyter notebook open on the side. Argues that every roadmap should start with a histogram and end with a follow-up question.",
    "Lives in three time zones and is somehow always the first to reply on Slack. Hobbies include long walks, longer postmortems, and convincing reviewers that this PR is, in fact, small.",
    "Joined for the coffee, stayed for the codebase. Has opinions on monorepos, file organization, and whether `index.ts` should be allowed to re-export anything at all (it should not).",
    "Quietly rewrote the deployment pipeline over a long weekend and never told anyone — found out three months later when the on-call rotation noticed the alert volume had dropped by 80%.",
];

// Date pool: small set of timestamps reused across rows to keep memory flat.
const datePool: Date[] = Array.from(
    { length: 60 },
    (_, i) => new Date(Date.now() - i * 86400000 * 5),
);

// Helper functions
function getRandomInt(min: number, max: number): number {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const names = ["Ennio", "Giovanni", "Mario", "Giuseppe"];
const statuses: Person["status"][] = ["active", "inactive", "pending"];

// Available tag options
const tagOptions = [
    { value: "vip", label: "VIP" },
    { value: "new", label: "New" },
    { value: "priority", label: "Priority" },
    { value: "archived", label: "Archived" },
    { value: "verified", label: "Verified" },
];

// Helper to get random tags
const getRandomTags = (): string[] => {
    const numTags = getRandomInt(0, 3);
    const shuffled = [...tagOptions].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, numTags).map((opt) => opt.value);
};

// Generate sample data (1.5M rows)
const generateRowData = (): Person[] =>
    Array.from({ length: 1500000 }, (_, i) => ({
        id: i + 1,
        name: `Person ${names[getRandomInt(0, 2)]}`,
        age: getRandomInt(18, 90),
        bio: bioPool[i % bioPool.length],
        createdAt: datePool[i % datePool.length],
        status: statuses[getRandomInt(0, 2)],
        salary: getRandomInt(30000, 150000),
        tags: getRandomTags(),
    }));

// Column definitions
const columns: ColumnDefinition[] = [
    {
        field: "id",
        cellDataType: "number",
        hidden: true,
        width: 80,
        headerName: "ID",
        cellRenderer: Bold,
    },
    { field: "name", editable: true, cellDataType: "text", width: 150, headerName: "Name" },
    {
        field: "age",
        cellDataType: "text",
        width: 150,
        headerName: "Age bucket",
        cellRenderer: AgeBucket,
        valueFormatter: (v) => {
            const n = typeof v === "number" ? v : Number(v);
            if (!Number.isFinite(n)) return "";
            if (n < 25) return "< 25";
            if (n < 40) return "25–39";
            if (n < 60) return "40–59";
            return "60+";
        },
    },
    {
        field: "bio",
        cellDataType: "text",
        width: 260,
        headerName: "Bio",
        distinctValues: bioPool,
        // wrapText: long text flows onto new lines (clipped to the fixed row
        // height) instead of truncating with an ellipsis.
        wrapText: true,
        // Not editable → double-click opens the read-only peek overlay
        // (once the Vue wrapper renders one — currently behaviour-only).
    },
    {
        field: "createdAt",
        cellDataType: "dateTime",
        width: 200,
        headerName: "Created",
        valueFormatter: (v) => (v instanceof Date ? v.toLocaleString() : ""),
    },
    {
        field: "status",
        cellDataType: "text",
        width: 120,
        headerName: "Status",
        cellRenderer: StatusBadge,
        valueFormatter: (v) => String(v ?? "").toUpperCase(),
    },
    {
        field: "salary",
        cellDataType: "number",
        width: 150,
        headerName: "Salary",
        cellRenderer: Currency,
    },
    {
        field: "tags",
        cellDataType: "object",
        width: 200,
        headerName: "Tags",
        cellRenderer: Tags,
        sortable: true,
    },
];

// Create data source via useGridData
const { dataSource, updateRow } = useGridData<Person>(generateRowData(), {
    getRowId: (row) => row.id,
});

const rowIdToUpdate = ref(1);

// Localized labels demo — override only what you need; the rest fall back to
// the English defaults.
const gridLabels: Partial<GridLabels> = {
    and: "E",
    filterTitle: "Filtra: {column}",
    apply: "Applica",
};

const handleUpdateRow = () => {
    updateRow(rowIdToUpdate.value, {
        name: `Person ${names[getRandomInt(0, 3)]}`,
        age: getRandomInt(18, 90),
        salary: getRandomInt(30000, 150000),
    });
};

const highlightingProps = computed<HighlightingOptions<Person>>(() => ({
    computeRowClasses:
        highlightMode.value === "row"
            ? (context) => {
                  if (context.isHovered) return ["row-highlight"];
                  return [];
              }
            : undefined,
    computeColumnClasses:
        highlightMode.value === "column"
            ? (context) => {
                  if (context.isHovered) return ["column-highlight"];
                  return [];
              }
            : undefined,
    computeCellClasses:
        highlightMode.value === "cell"
            ? (context) => {
                  if (context.isHovered) return ["cell-highlight"];
                  return [];
              }
            : undefined,
}));
</script>

<template>
    <div>
        <a href="https://vite.dev" target="_blank">
            <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://vuejs.org/" target="_blank">
            <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
        </a>
    </div>
    <h1>GP Grid Vue Demo</h1>

    <h2 class="subtitle">Large Dataset Demo (1.5M rows)</h2>

    <!-- Highlight Mode Switcher -->
    <div class="mode-switcher">
        <span class="mode-label">Highlight Mode:</span>
        <button
            v-for="mode in ['row', 'column', 'cell'] as const"
            :key="mode"
            @click="highlightMode = mode"
            :class="['mode-btn', { active: highlightMode === mode }]"
        >
            {{ mode.charAt(0).toUpperCase() + mode.slice(1) }} Hover
        </button>
    </div>

    <div class="grid-container">
        <GpGrid
            :row-drag-entire-row="true"
            :highlighting="highlightingProps"
            :columns="columns"
            :labels="gridLabels"
            :overscan="12"
            :data-source="dataSource"
            :row-height="36"
            :header-height="40"
            :dark-mode="true"
        />
    </div>

    <div class="card">
        <input
            type="number"
            :value="rowIdToUpdate"
            @input="
                (e) =>
                    (rowIdToUpdate = Number(
                        (e.target as HTMLInputElement).value,
                    ))
            "
            :min="1"
            :max="1500000"
            class="row-id-input"
        />
        <button class="update-row-btn" @click="handleUpdateRow">
            Update Row {{ rowIdToUpdate }}
        </button>
        <p class="hint">
            Double-click cells to edit (Name/Tags), or Bio for a read-only peek
            overlay
        </p>
    </div>

    <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
}
.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}

.subtitle {
    margin-bottom: 16px;
    color: #f3f4f6;
}

.grid-container {
    width: 1000px;
    height: 400px;
}

.card {
    display: flex;
    gap: 12px;
    align-items: center;
    padding: 2em;
}

.row-id-input {
    width: 100px;
    padding: 8px;
    border-radius: 6px;
    border: 1px solid #4b5563;
    background-color: #1f2937;
    color: #f3f4f6;
}

.update-row-btn {
    background-color: #6366f1;
    color: white;
    padding: 8px 16px;
    border-radius: 6px;
    border: none;
    cursor: pointer;
    font-weight: 500;
}

.update-row-btn:hover {
    background-color: #4f46e5;
}

.hint {
    margin: 0;
    color: #9ca3af;
}

.read-the-docs {
    color: #888;
}

/* Highlight mode switcher */
.mode-switcher {
    margin-bottom: 12px;
    display: flex;
    gap: 8px;
    align-items: center;
}

.mode-label {
    color: #9ca3af;
    margin-right: 8px;
}

.mode-btn {
    padding: 6px 12px;
    border-radius: 4px;
    border: none;
    cursor: pointer;
    font-weight: 400;
    background-color: #374151;
    color: #9ca3af;
}

.mode-btn.active {
    font-weight: 600;
    background-color: #3b82f6;
    color: white;
}
</style>

<style>
/* Highlight classes (global, not scoped) */
.row-highlight {
    background-color: rgba(59, 130, 246, 0.3) !important;
}

.column-highlight {
    background-color: rgba(16, 185, 129, 0.3) !important;
}

.cell-highlight {
    background-color: rgba(245, 158, 11, 0.5) !important;
}
</style>
