// playgrounds/vite-react/src/App.tsx
import { useState, useMemo } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import {
  Grid,
  useGridData,
  type ColumnDefinition,
  type CellRendererParams,
  type EditRendererParams,
  type RowId,
  type CellValueChangedEvent,
} from "@gp-grid/react";
import Select from "react-select";
import { LiveInsertDemo } from "./LiveInsertDemo";

type DemoPage = "main" | "live-insert";

interface Person {
  id: number;
  name: string;
  age: number;
  bio: string;
  createdAt: Date;
  status: "active" | "inactive" | "pending";
  salary: number;
  tags: string[];
}

// Long bio strings pooled so the 1.5M-row dataset doesn't allocate millions of
// distinct strings. Each row references one of these by index modulo.
const bioPool: string[] = [
  "Seasoned backend engineer who spent the last decade chasing tail-latency outliers across distributed message brokers. Mentors junior engineers, writes too many internal docs, and is on a quiet mission to retire every YAML file in the company.",
  "Joined fresh out of a bootcamp three years ago and now leads the design system working group. Holds strong opinions about color tokens, accessible focus rings, and the perfect motion duration (always 180ms, never 200).",
  "Former data scientist turned product manager. Still keeps a Jupyter notebook open on the side. Argues that every roadmap should start with a histogram and end with a follow-up question.",
  "Lives in three time zones and is somehow always the first to reply on Slack. Hobbies include long walks, longer postmortems, and convincing reviewers that this PR is, in fact, small.",
  "Joined for the coffee, stayed for the codebase. Has opinions on monorepos, file organization, and whether `index.ts` should be allowed to re-export anything at all (it should not).",
  "Quietly rewrote the deployment pipeline over a long weekend and never told anyone — found out three months later when the on-call rotation noticed the alert volume had dropped by 80%.",
];

// Date pool: small set of timestamps reused across rows to keep memory flat.
const datePool: Date[] = Array.from(
  { length: 60 },
  (_, i) => new Date(Date.now() - i * 86400000 * 5),
);

const getRowId = (person: Person): RowId => {
  return person.id;
};

const onCellUpdate = (context: CellValueChangedEvent<Person>): void => {
  console.log(`Old value was ${context.oldValue} and new value is ${context.newValue}`);
  return;
}

// Available tag options for the multi-select
const tagOptions = [
  { value: "vip", label: "VIP" },
  { value: "new", label: "New" },
  { value: "priority", label: "Priority" },
  { value: "archived", label: "Archived" },
  { value: "verified", label: "Verified" },
];

function getRandomInt(min: number, max: number): number {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const names = ["Ennio", "Giovanni", "Mario", "Giuseppe"];
const statuses: Person["status"][] = ["active", "inactive", "pending"];

// Define reusable React renderers 
const cellRenderers = {
  // Currency formatter - reusable for multiple columns
  currency: (params: CellRendererParams) => {
    const value = params.value as number;
    return (
      <span style={{ color: "#047857", fontWeight: "600" }}>
        ${value.toLocaleString("en-US", { minimumFractionDigits: 2 })}
      </span>
    );
  },

  // Status badge - styled pill
  statusBadge: (params: CellRendererParams) => {
    // Raw value drives the color variant; params.value may be the formatted
    // display string when the column declares a valueFormatter.
    const rawStatus = (params.rowData as Person)[
      params.column.field as keyof Person
    ] as Person["status"];
    const colors = {
      active: { bg: "#dcfce7", text: "#166534" },
      inactive: { bg: "#fee2e2", text: "#991b1b" },
      pending: { bg: "#fef3c7", text: "#92400e" },
    };
    const color = colors[rawStatus];

    return (
      <span
        style={{
          backgroundColor: color.bg,
          color: color.text,
          padding: "2px 8px",
          borderRadius: "12px",
          fontSize: "12px",
          fontWeight: "600",
        }}
      >
        {String(params.value ?? "")}
      </span>
    );
  },

  // Bold text renderer
  bold: (params: CellRendererParams) => {
    return <strong>{String(params.value ?? "")}</strong>;
  },

  // Tags renderer - displays tags as badges with vertical scroll
  tags: (params: CellRendererParams) => {
    const tags = (params.value as string[]) || [];
    if (tags.length === 0) {
      return (
        <span style={{ color: "#6b7280", fontStyle: "italic" }}>No tags</span>
      );
    }
    return (
      <div
        style={{
          display: "flex",
          gap: "4px",
          flexWrap: "wrap",
          maxHeight: "100%",
          overflowY: "auto",
          alignContent: "flex-start",
          padding: "2px 0",
        }}
      >
        {tags.map((tag) => (
          <span
            key={tag}
            style={{
              backgroundColor: "#3b82f6",
              color: "#ffffff",
              padding: "2px 6px",
              borderRadius: "4px",
              fontSize: "11px",
              fontWeight: "500",
              flexShrink: 0,
            }}
          >
            {tag.toUpperCase()}
          </span>
        ))}
      </div>
    );
  },
};

// Multi-select editor component with local state for live updates
function MultiSelectEditor({ params }: { params: EditRendererParams }) {
  const initialTags = (params.initialValue as string[]) || [];
  const [selectedTags, setSelectedTags] = useState<string[]>(initialTags);

  const selectedOptions = tagOptions.filter((opt) =>
    selectedTags.includes(opt.value),
  );

  const handleChange = (
    newValue: readonly { value: string; label: string }[],
  ) => {
    const newTags = newValue.map((opt) => opt.value);
    setSelectedTags(newTags);
    params.onValueChange(newTags);
  };

  return (
    <Select
      isMulti
      autoFocus
      menuIsOpen
      options={tagOptions}
      value={selectedOptions}
      onChange={handleChange}
      onBlur={() => params.onCommit()}
      onKeyDown={(e) => {
        if (e.key === "Escape") {
          params.onCancel();
        }
      }}
      // Use portal to render dropdown outside the cell's overflow:hidden
      menuPortalTarget={document.body}
      menuPosition="fixed"
      styles={{
        container: (base) => ({
          ...base,
          width: "100%",
          height: "32px", // Match row height minus border
        }),
        control: (base) => ({
          ...base,
          minHeight: "32px",
          height: "32px",
          backgroundColor: "#1f2937",
          borderColor: "#3b82f6",
          boxShadow: "0 0 0 1px #3b82f6",
          alignItems: "flex-start",
          border: "none",
        }),
        valueContainer: (base) => ({
          ...base,
          height: "30px",
          maxHeight: "30px",
          overflowY: "auto",
          overflowX: "hidden",
          flexWrap: "wrap",
          alignContent: "flex-start",
          padding: "2px 8px",
        }),
        indicatorsContainer: (base) => ({
          ...base,
          height: "32px",
        }),
        menu: (base) => ({
          ...base,
          backgroundColor: "#1f2937",
          zIndex: 9999,
        }),
        menuPortal: (base) => ({
          ...base,
          zIndex: 9999,
        }),
        option: (base, state) => ({
          ...base,
          backgroundColor: state.isFocused ? "#374151" : "#1f2937",
          color: "#f3f4f6",
          cursor: "pointer",
        }),
        multiValue: (base) => ({
          ...base,
          backgroundColor: "#3b82f6",
          margin: "1px 2px",
        }),
        multiValueLabel: (base) => ({
          ...base,
          color: "#ffffff",
          padding: "1px 4px",
          fontSize: "11px",
        }),
        multiValueRemove: (base) => ({
          ...base,
          color: "#ffffff",
          padding: "0 2px",
          ":hover": {
            backgroundColor: "#2563eb",
            color: "#ffffff",
          },
        }),
        input: (base) => ({
          ...base,
          color: "#f3f4f6",
          margin: "0",
          padding: "0",
        }),
      }}
    />
  );
}

// Define edit renderers
const editRenderers = {
  multiSelect: (params: EditRendererParams) => (
    <MultiSelectEditor params={params} />
  ),
};

const columns: ColumnDefinition[] = [
  {
    field: "id",
    cellDataType: "number",
    width: 80,
    headerName: "ID",
    cellRenderer: "bold", // Reference renderer by key
  },
  {
    field: "name",
    editable: true,
    cellDataType: "text",
    width: 150,
    headerName: "Name",
  },
  {
    field: "age",
    cellDataType: "text",
    width: 130,
    headerName: "Age bucket",
    valueFormatter: (v) => {
      const n = typeof v === "number" ? v : Number(v);
      if (!Number.isFinite(n)) return "";
      if (n < 25) return "< 25";
      if (n < 40) return "25–39";
      if (n < 60) return "40–59";
      return "60+";
    },
  },
  {
    field: "bio",
    cellDataType: "text",
    width: 260,
    headerName: "Bio",
    distinctValues: bioPool,
    // Not editable → double-click opens the read-only peek overlay so
    // the full multi-line value can be read without changing row height.
  },
  {
    field: "createdAt",
    cellDataType: "dateTime",
    width: 200,
    headerName: "Created",
    valueFormatter: (v) => (v instanceof Date ? v.toLocaleString() : ""),
  },
  {
    field: "status",
    cellDataType: "text",
    width: 120,
    headerName: "Status",
    cellRenderer: "statusBadge", // Reference renderer by key
    valueFormatter: (v) => String(v ?? "").toUpperCase(),
  },
  {
    field: "salary",
    cellDataType: "number",
    width: 150,
    headerName: "Salary",
    cellRenderer: "currency", // Reference renderer by key
  },
  {
    field: "tags",
    cellDataType: "object",
    width: 200,
    headerName: "Tags",
    cellRenderer: "tags",
    editRenderer: "multiSelect",
    editable: true,
    sortable: true,
  },
];

// Helper to get random tags
const getRandomTags = (): string[] => {
  const numTags = getRandomInt(0, 3);
  const shuffled = [...tagOptions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, numTags).map((opt) => opt.value);
};

// Generate sample data
const generateRowData = (): Person[] =>
  Array.from({ length: 1500000 }, (_, i) => ({
    id: i + 1,
    name: `Person ${names[getRandomInt(0, 2)]}`,
    age: getRandomInt(18, 90),
    bio: bioPool[i % bioPool.length],
    createdAt: datePool[i % datePool.length],
    status: statuses[getRandomInt(0, 2)],
    salary: getRandomInt(30000, 150000),
    tags: getRandomTags(),
  }));

type HighlightMode = "row" | "column" | "cell";

const initialRowData = generateRowData();

function MainDemo() {
  const [count, setCount] = useState(0);
  const [highlightMode, setHighlightMode] = useState<HighlightMode>("row");
  const [rowIdToUpdate, setRowIdToUpdate] = useState(1);

  const { dataSource, updateRow } = useGridData<Person>(
    initialRowData,
    { getRowId: (row) => row.id },
  );

  const highlighting = useMemo(() => ({
    computeRowClasses: highlightMode === "row" ? (context: { isHovered: boolean }) => {
      if (context.isHovered) return ["row-highlight"];
      return [];
    } : undefined,
    computeColumnClasses: highlightMode === "column" ? (context: { isHovered: boolean }) => {
      if (context.isHovered) return ["column-highlight"];
      return [];
    } : undefined,
    computeCellClasses: highlightMode === "cell" ? (context: { isHovered: boolean }) => {
      if (context.isHovered) return ["cell-highlight"];
      return [];
    } : undefined,
  }), [highlightMode]);

  const handleUpdateRow = () => {
    updateRow(rowIdToUpdate, {
      name: `Person ${names[getRandomInt(0, 3)]}`,
      salary: getRandomInt(30000, 150000),
    });
  };

  return (
    <>
      <h2 style={{ marginBottom: "16px", color: "#f3f4f6" }}>
        Large Dataset Demo (1.5M rows)
      </h2>
      {/* Highlight Mode Switcher */}
      <div style={{ marginBottom: "12px", display: "flex", gap: "8px" }}>
        <span style={{ color: "#9ca3af", marginRight: "8px" }}>Highlight Mode:</span>
        {(["row", "column", "cell"] as const).map((mode) => (
          <button
            key={mode}
            onClick={() => setHighlightMode(mode)}
            style={{
              padding: "6px 12px",
              borderRadius: "4px",
              border: "none",
              cursor: "pointer",
              fontWeight: highlightMode === mode ? "600" : "400",
              backgroundColor: highlightMode === mode ? "#3b82f6" : "#374151",
              color: highlightMode === mode ? "white" : "#9ca3af",
            }}
          >
            {mode.charAt(0).toUpperCase() + mode.slice(1)} Hover
          </button>
        ))}
      </div>

      <div style={{ width: "1000px", height: "400px" }}>
        <Grid
          highlighting={highlighting}
          getRowId={getRowId}
          onCellValueChanged={onCellUpdate}
          columns={columns}
          dataSource={dataSource}
          rowHeight={36}
          darkMode={true}
          headerHeight={40}
          cellRenderers={cellRenderers}
          editRenderers={editRenderers}
          rowDragEntireRow
          onRowDragEnd={(src, tgt) => console.log(`Row drag: ${src} → ${tgt}`)}
        />
      </div>
      <div
        className="card"
        style={{ display: "flex", gap: "12px", alignItems: "center" }}
      >
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <input
          type="number"
          value={rowIdToUpdate}
          onChange={(e) => setRowIdToUpdate(Number(e.target.value))}
          min={1}
          max={1500000}
          style={{
            width: "100px",
            padding: "8px",
            borderRadius: "6px",
            border: "1px solid #4b5563",
            backgroundColor: "#1f2937",
            color: "#f3f4f6",
          }}
        />
        <button
          onClick={handleUpdateRow}
          style={{
            backgroundColor: "#6366f1",
            color: "white",
            padding: "8px 16px",
            borderRadius: "6px",
            border: "none",
            cursor: "pointer",
            fontWeight: "500",
          }}
        >
          Update Row {rowIdToUpdate}
        </button>
        <p style={{ margin: 0 }}>
          Double-click Tags to edit, or Bio for a read-only peek overlay
        </p>
      </div>
    </>
  );
}

function App() {
  const [currentPage, setCurrentPage] = useState<DemoPage>("main");

  const tabStyle = (isActive: boolean) => ({
    padding: "10px 20px",
    border: "none",
    borderBottom: isActive ? "3px solid #3b82f6" : "3px solid transparent",
    backgroundColor: "transparent",
    color: isActive ? "#3b82f6" : "#9ca3af",
    cursor: "pointer",
    fontWeight: isActive ? "600" : "400",
    fontSize: "14px",
    transition: "all 0.2s",
  });

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>GP Grid Demo</h1>

      <div
        style={{
          display: "flex",
          gap: "4px",
          marginBottom: "24px",
          borderBottom: "1px solid #374151",
        }}
      >
        <button
          onClick={() => setCurrentPage("main")}
          style={tabStyle(currentPage === "main")}
        >
          Large Dataset
        </button>
        <button
          onClick={() => setCurrentPage("live-insert")}
          style={tabStyle(currentPage === "live-insert")}
        >
          Live Insert
        </button>
      </div>

      {currentPage === "main" && <MainDemo />}
      {currentPage === "live-insert" && <LiveInsertDemo />}

      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}

export default App;

// playgrounds/vite-vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import {
    GpGrid,
    useGridData,
    type ColumnDefinition,
    type HighlightingOptions,
} from "@gp-grid/vue";
import Currency from "./renderers/Currency.vue";
import StatusBadge from "./renderers/StatusBadge.vue";
import Bold from "./renderers/Bold.vue";
import Tags from "./renderers/Tags.vue";
import AgeBucket from "./renderers/AgeBucket.vue";
type HighlightMode = "row" | "column" | "cell";
const highlightMode = ref<HighlightMode>("row");

// Types
interface Person {
    id: number;
    name: string;
    age: number;
    bio: string;
    createdAt: Date;
    status: "active" | "inactive" | "pending";
    salary: number;
    tags: string[];
}

// Long bio strings pooled so the 1.5M-row dataset doesn't allocate millions of
// distinct strings. Each row references one of these by index modulo.
const bioPool: string[] = [
    "Seasoned backend engineer who spent the last decade chasing tail-latency outliers across distributed message brokers. Mentors junior engineers, writes too many internal docs, and is on a quiet mission to retire every YAML file in the company.",
    "Joined fresh out of a bootcamp three years ago and now leads the design system working group. Holds strong opinions about color tokens, accessible focus rings, and the perfect motion duration (always 180ms, never 200).",
    "Former data scientist turned product manager. Still keeps a Jupyter notebook open on the side. Argues that every roadmap should start with a histogram and end with a follow-up question.",
    "Lives in three time zones and is somehow always the first to reply on Slack. Hobbies include long walks, longer postmortems, and convincing reviewers that this PR is, in fact, small.",
    "Joined for the coffee, stayed for the codebase. Has opinions on monorepos, file organization, and whether `index.ts` should be allowed to re-export anything at all (it should not).",
    "Quietly rewrote the deployment pipeline over a long weekend and never told anyone — found out three months later when the on-call rotation noticed the alert volume had dropped by 80%.",
];

// Date pool: small set of timestamps reused across rows to keep memory flat.
const datePool: Date[] = Array.from(
    { length: 60 },
    (_, i) => new Date(Date.now() - i * 86400000 * 5),
);

// Helper functions
function getRandomInt(min: number, max: number): number {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const names = ["Ennio", "Giovanni", "Mario", "Giuseppe"];
const statuses: Person["status"][] = ["active", "inactive", "pending"];

// Available tag options
const tagOptions = [
    { value: "vip", label: "VIP" },
    { value: "new", label: "New" },
    { value: "priority", label: "Priority" },
    { value: "archived", label: "Archived" },
    { value: "verified", label: "Verified" },
];

// Helper to get random tags
const getRandomTags = (): string[] => {
    const numTags = getRandomInt(0, 3);
    const shuffled = [...tagOptions].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, numTags).map((opt) => opt.value);
};

// Generate sample data (1.5M rows)
const generateRowData = (): Person[] =>
    Array.from({ length: 1500000 }, (_, i) => ({
        id: i + 1,
        name: `Person ${names[getRandomInt(0, 2)]}`,
        age: getRandomInt(18, 90),
        bio: bioPool[i % bioPool.length],
        createdAt: datePool[i % datePool.length],
        status: statuses[getRandomInt(0, 2)],
        salary: getRandomInt(30000, 150000),
        tags: getRandomTags(),
    }));

// Column definitions
const columns: ColumnDefinition[] = [
    {
        field: "id",
        cellDataType: "number",
        hidden: true,
        width: 80,
        headerName: "ID",
        cellRenderer: Bold,
    },
    { field: "name", editable: true, cellDataType: "text", width: 150, headerName: "Name" },
    {
        field: "age",
        cellDataType: "text",
        width: 150,
        headerName: "Age bucket",
        cellRenderer: AgeBucket,
        valueFormatter: (v) => {
            const n = typeof v === "number" ? v : Number(v);
            if (!Number.isFinite(n)) return "";
            if (n < 25) return "< 25";
            if (n < 40) return "25–39";
            if (n < 60) return "40–59";
            return "60+";
        },
    },
    {
        field: "bio",
        cellDataType: "text",
        width: 260,
        headerName: "Bio",
        distinctValues: bioPool,
        // Not editable → double-click opens the read-only peek overlay
        // (once the Vue wrapper renders one — currently behaviour-only).
    },
    {
        field: "createdAt",
        cellDataType: "dateTime",
        width: 200,
        headerName: "Created",
        valueFormatter: (v) => (v instanceof Date ? v.toLocaleString() : ""),
    },
    {
        field: "status",
        cellDataType: "text",
        width: 120,
        headerName: "Status",
        cellRenderer: StatusBadge,
        valueFormatter: (v) => String(v ?? "").toUpperCase(),
    },
    {
        field: "salary",
        cellDataType: "number",
        width: 150,
        headerName: "Salary",
        cellRenderer: Currency,
    },
    {
        field: "tags",
        cellDataType: "object",
        width: 200,
        headerName: "Tags",
        cellRenderer: Tags,
        sortable: true,
    },
];

// Create data source via useGridData
const { dataSource, updateRow } = useGridData<Person>(generateRowData(), {
    getRowId: (row) => row.id,
});

const rowIdToUpdate = ref(1);

const handleUpdateRow = () => {
    updateRow(rowIdToUpdate.value, {
        name: `Person ${names[getRandomInt(0, 3)]}`,
        age: getRandomInt(18, 90),
        salary: getRandomInt(30000, 150000),
    });
};

const highlightingProps = computed<HighlightingOptions<Person>>(() => ({
    computeRowClasses:
        highlightMode.value === "row"
            ? (context) => {
                  if (context.isHovered) return ["row-highlight"];
                  return [];
              }
            : undefined,
    computeColumnClasses:
        highlightMode.value === "column"
            ? (context) => {
                  if (context.isHovered) return ["column-highlight"];
                  return [];
              }
            : undefined,
    computeCellClasses:
        highlightMode.value === "cell"
            ? (context) => {
                  if (context.isHovered) return ["cell-highlight"];
                  return [];
              }
            : undefined,
}));
</script>

<template>
    <div>
        <a href="https://vite.dev" target="_blank">
            <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://vuejs.org/" target="_blank">
            <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
        </a>
    </div>
    <h1>GP Grid Vue Demo</h1>

    <h2 class="subtitle">Large Dataset Demo (1.5M rows)</h2>

    <!-- Highlight Mode Switcher -->
    <div class="mode-switcher">
        <span class="mode-label">Highlight Mode:</span>
        <button
            v-for="mode in ['row', 'column', 'cell'] as const"
            :key="mode"
            @click="highlightMode = mode"
            :class="['mode-btn', { active: highlightMode === mode }]"
        >
            {{ mode.charAt(0).toUpperCase() + mode.slice(1) }} Hover
        </button>
    </div>

    <div class="grid-container">
        <GpGrid
            :row-drag-entire-row="true"
            :highlighting="highlightingProps"
            :columns="columns"
            :data-source="dataSource"
            :row-height="36"
            :header-height="40"
            :dark-mode="true"
        />
    </div>

    <div class="card">
        <input
            type="number"
            :value="rowIdToUpdate"
            @input="
                (e) =>
                    (rowIdToUpdate = Number(
                        (e.target as HTMLInputElement).value,
                    ))
            "
            :min="1"
            :max="1500000"
            class="row-id-input"
        />
        <button class="update-row-btn" @click="handleUpdateRow">
            Update Row {{ rowIdToUpdate }}
        </button>
        <p class="hint">
            Double-click cells to edit (Name/Tags), or Bio for a read-only peek
            overlay
        </p>
    </div>

    <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
}
.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}

.subtitle {
    margin-bottom: 16px;
    color: #f3f4f6;
}

.grid-container {
    width: 1000px;
    height: 400px;
}

.card {
    display: flex;
    gap: 12px;
    align-items: center;
    padding: 2em;
}

.row-id-input {
    width: 100px;
    padding: 8px;
    border-radius: 6px;
    border: 1px solid #4b5563;
    background-color: #1f2937;
    color: #f3f4f6;
}

.update-row-btn {
    background-color: #6366f1;
    color: white;
    padding: 8px 16px;
    border-radius: 6px;
    border: none;
    cursor: pointer;
    font-weight: 500;
}

.update-row-btn:hover {
    background-color: #4f46e5;
}

.hint {
    margin: 0;
    color: #9ca3af;
}

.read-the-docs {
    color: #888;
}

/* Highlight mode switcher */
.mode-switcher {
    margin-bottom: 12px;
    display: flex;
    gap: 8px;
    align-items: center;
}

.mode-label {
    color: #9ca3af;
    margin-right: 8px;
}

.mode-btn {
    padding: 6px 12px;
    border-radius: 4px;
    border: none;
    cursor: pointer;
    font-weight: 400;
    background-color: #374151;
    color: #9ca3af;
}

.mode-btn.active {
    font-weight: 600;
    background-color: #3b82f6;
    color: white;
}
</style>

<style>
/* Highlight classes (global, not scoped) */
.row-highlight {
    background-color: rgba(59, 130, 246, 0.3) !important;
}

.column-highlight {
    background-color: rgba(16, 185, 129, 0.3) !important;
}

.cell-highlight {
    background-color: rgba(245, 158, 11, 0.5) !important;
}
</style>
