// packages/react/src/components/GridCell.tsx
// packages/react/src/components/GridCell.tsx

import React from "react";
import type {
  GridCore,
  CellPosition,
  CellRange,
  CellValue,
  DragState,
  ResolvedColumn,
} from "@gp-grid/core";
import {
  isCellSelected,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  buildCellClasses,
  formatCellValue,
} from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import { renderEditCell } from "../renderers/editRenderer";
import type { ReactCellRenderer, ReactEditRenderer } from "../types";

export interface GridCellProps<TData = unknown> {
  rowIndex: number;
  rowData: TData | undefined;
  column: ResolvedColumn;
  /** 0-based index in the displayed columns, for `aria-colindex`. */
  displayedIndex: number;
  rowHeight: number;
  activeCell: CellPosition | null;
  selectionRange: CellRange | null;
  editingCell: { row: number; col: number; initialValue: CellValue; editId: number } | null;
  dragState: DragState;
  coreRef: React.RefObject<GridCore<TData> | null>;
  cellRenderers: Record<string, ReactCellRenderer>;
  editRenderers: Record<string, ReactEditRenderer>;
  globalCellRenderer?: ReactCellRenderer;
  globalEditRenderer?: ReactEditRenderer;
  onCellMouseDown: (rowIndex: number, colIndex: number, e: React.PointerEvent) => void;
  onCellDoubleClick: (rowIndex: number, colIndex: number) => void;
  onCellMouseEnter: (rowIndex: number, colIndex: number) => void;
  onCellMouseLeave: () => void;
}

/**
 * One body cell. `insetInlineStart` is region-local, so the same markup renders
 * inside a pin container and as an absolute center cell.
 */
export const GridCell = <TData = unknown>(
  props: GridCellProps<TData>,
): React.ReactNode => {
  const {
    rowIndex,
    rowData,
    column,
    displayedIndex,
    rowHeight,
    activeCell,
    selectionRange,
    editingCell,
    dragState,
    coreRef,
    cellRenderers,
    editRenderers,
    globalCellRenderer,
    globalEditRenderer,
    onCellMouseDown,
    onCellDoubleClick,
    onCellMouseEnter,
    onCellMouseLeave,
  } = props;

  const { column: definition, layoutIndex, width, regionOffset } = column;
  const core = coreRef.current;

  const isEditing = isCellEditing(rowIndex, layoutIndex, editingCell);
  const liveEdit = isEditing ? core?.edit.getState() : null;
  const active = isCellActive(rowIndex, layoutIndex, activeCell);
  const selected = isCellSelected(rowIndex, layoutIndex, selectionRange);
  const inFillPreview = isCellInFillPreview(
    rowIndex,
    layoutIndex,
    dragState.dragType === "fill",
    dragState.fillSourceRange,
    dragState.fillTarget,
  );

  const highlightCellClasses =
    coreRef.current?.highlight?.computeCombinedCellClasses(
      rowIndex,
      layoutIndex,
      definition,
      rowData,
    ) ?? [];

  // Read the raw value through the core read path so a record-less (columnar)
  // row renders like an object row.
  const rawValue = core?.cells.getValue(rowIndex, layoutIndex) ?? null;
  const rowId = core?.rows.getId(rowIndex);
  const getValue = (field: string): CellValue =>
    core?.cells.getFieldValue(rowIndex, field) ?? null;

  // Wrap only affects the default text content, so it is irrelevant (and would
  // clash with the edit input) in edit mode.
  const wrapText = definition.wrapText === true && !isEditing;

  const cellClasses = [
    buildCellClasses(active, selected, isEditing, inFillPreview),
    ...highlightCellClasses,
    definition.rowDrag === true ? "gp-grid-cell--row-drag-handle" : "",
    wrapText ? "gp-grid-cell--wrap" : "",
  ]
    .filter(Boolean)
    .join(" ");

  // Native tooltip: show the formatted value on hover so users can read
  // content that's clipped by the cell width. Opt out per column with
  // `tooltip: false`. Suppressed while editing (the input shows its value).
  const titleText =
    definition.tooltip === false || isEditing
      ? ""
      : formatCellValue(rawValue, definition.valueFormatter);

  return (
    <div
      className={cellClasses}
      role="gridcell"
      aria-colindex={displayedIndex + 1}
      data-cell-row={rowIndex}
      data-cell-col={layoutIndex}
      data-cell-region={column.region}
      title={titleText || undefined}
      style={{
        position: "absolute",
        insetInlineStart: `${regionOffset}px`,
        top: 0,
        width: `${width}px`,
        height: `${rowHeight}px`,
      }}
      onPointerDown={(e) => onCellMouseDown(rowIndex, layoutIndex, e)}
      onDoubleClick={() => onCellDoubleClick(rowIndex, layoutIndex)}
      onMouseEnter={() => onCellMouseEnter(rowIndex, layoutIndex)}
      onMouseLeave={onCellMouseLeave}
    >
      {isEditing && editingCell
        ? renderEditCell({
          column: definition,
          rowData,
          rawValue,
          rowId,
          getValue,
          rowIndex,
          colIndex: layoutIndex,
          initialValue:
            liveEdit?.editId === editingCell.editId
              ? liveEdit.currentValue
              : editingCell.initialValue,
          editId: editingCell.editId,
          coreRef,
          editRenderers,
          globalEditRenderer,
        })
        : renderCell({
          column: definition,
          rowData,
          rawValue,
          rowId,
          getValue,
          rowIndex,
          colIndex: layoutIndex,
          isActive: active,
          isSelected: selected,
          isEditing,
          cellRenderers,
          globalCellRenderer,
        })}
    </div>
  );
};

// packages/vue/src/components/GridCell.vue
<script setup lang="ts">
import type { CellValue, ColumnDefinition } from "@gp-grid/core";
import {
  buildCellClasses,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  isCellSelected,
} from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import { renderEditCell } from "../renderers/editRenderer";
import type { GridCellProps } from "./cell-props";

const props = defineProps<GridCellProps>();

// Region-local inset: the same markup renders inside a pin container and as an
// absolute center cell.
const getCellClasses = (): string => {
  const { rowIndex, column, rowData } = props;
  // Registers the hover signal as a dependency: highlight classes read live
  // core state, which is not reactive on its own.
  void props.hoverPosition;
  const definition: ColumnDefinition = column.column;
  const isEditing = isCellEditing(rowIndex, column.layoutIndex, props.editingCell);
  const active = isCellActive(rowIndex, column.layoutIndex, props.activeCell);
  const selected = isCellSelected(rowIndex, column.layoutIndex, props.selectionRange);
  const inFillPreview = isCellInFillPreview(
    rowIndex,
    column.layoutIndex,
    props.dragState.dragType === "fill",
    props.dragState.fillSourceRange,
    props.dragState.fillTarget,
  );

  const highlightCellClasses =
    props.coreRef?.highlight?.computeCombinedCellClasses(
      rowIndex,
      column.layoutIndex,
      definition,
      rowData,
    ) ?? [];

  // Wrap only affects the default text content, so it is irrelevant (and would
  // clash with the edit input) in edit mode.
  const wrapText = definition.wrapText === true && !isEditing;

  return [
    buildCellClasses(active, selected, isEditing, inFillPreview),
    ...highlightCellClasses,
    definition.rowDrag === true ? "gp-grid-cell--row-drag-handle" : "",
    wrapText ? "gp-grid-cell--wrap" : "",
  ].filter(Boolean).join(" ");
};

const isEditing = (): boolean =>
  isCellEditing(props.rowIndex, props.column.layoutIndex, props.editingCell);

// Read raw values through the core so a record-less (columnar) row renders
// exactly like an object row.
const getRawValue = (): CellValue =>
  props.coreRef?.cells.getValue(props.rowIndex, props.column.layoutIndex) ?? null;

const getRowIdAt = () => props.coreRef?.rows.getId(props.rowIndex);

const getFieldValueAt = (field: string): CellValue =>
  props.coreRef?.cells.getFieldValue(props.rowIndex, field) ?? null;

/** The open editor is the source of truth for its draft value. */
const initialEditValue = (): CellValue => {
  const editing = props.editingCell;
  if (editing === null) return null;
  const live = props.coreRef?.edit.getState() ?? null;
  if (live !== null && live.editId === editing.editId) return live.currentValue;
  return editing.initialValue;
};

const cellContent = () => {
  const { column, rowData } = props;
  void props.renderToken;
  const definition = column.column;
  const editing = props.editingCell;
  if (isEditing() && editing) {
    return renderEditCell({
      column: definition,
      rowData,
      rawValue: getRawValue(),
      rowId: getRowIdAt(),
      getValue: getFieldValueAt,
      rowIndex: props.rowIndex,
      colIndex: column.layoutIndex,
      initialValue: initialEditValue(),
      editId: editing.editId,
      core: props.coreRef,
      editRenderers: props.editRenderers,
      globalEditRenderer: props.globalEditRenderer,
    });
  }
  return renderCell({
    column: definition,
    rowData,
    rawValue: getRawValue(),
    rowId: getRowIdAt(),
    getValue: getFieldValueAt,
    rowIndex: props.rowIndex,
    colIndex: column.layoutIndex,
    isActive: isCellActive(props.rowIndex, column.layoutIndex, props.activeCell),
    isSelected: isCellSelected(props.rowIndex, column.layoutIndex, props.selectionRange),
    isEditing: false,
    cellRenderers: props.cellRenderers,
    globalCellRenderer: props.globalCellRenderer,
  });
};
</script>

<template>
  <div
    :class="getCellClasses()"
    role="gridcell"
    :aria-colindex="props.displayedIndex + 1"
    :data-cell-row="props.rowIndex"
    :data-cell-col="props.column.layoutIndex"
    :data-cell-region="props.column.region"
    :style="{
      position: 'absolute',
      insetInlineStart: `${props.column.regionOffset}px`,
      top: 0,
      width: `${props.column.width}px`,
      height: `${props.rowHeight}px`,
    }"
    @pointerdown="(e) => props.onCellMouseDown(props.rowIndex, props.column.layoutIndex, e)"
    @dblclick="() => props.onCellDoubleClick(props.rowIndex, props.column.layoutIndex)"
    @mouseenter="() => props.onCellMouseEnter(props.rowIndex, props.column.layoutIndex)"
    @mouseleave="props.onCellMouseLeave"
  >
    <component :is="cellContent()" />
  </div>
</template>
