// packages/vue/src/GpGrid.vue
<script setup lang="ts">
import {
  ref,
  shallowRef,
  computed,
  onMounted,
  onUnmounted,
  watch,
} from "vue";
import {
  GridCore,
  createClientDataSource,
  createDataSourceFromArray,
  readIsRtl,
  toInlineX,
  toPhysicalX,
  TouchScrollController,
  PendingScrollLatch,
  defaultPinIcon,
  resolveGridLabels,
  createDomMeasurementHost,
} from "@gp-grid/core";
import type { Component } from "vue";
import type { AutoFitOptions, RowId, RowResizedEvent, ColumnFilterModel, ColumnGroupChild, ColumnGroupLimits, ColumnSchemaError, ColumnLayoutMode, ColumnMovedEvent, ColumnPinnedEvent, ColumnResizedEvent, ColumnStateUpdate, DataSource, CellValueChangedEvent, CellWriteRejectedEvent, FreezeRowsOptions, FrozenRowsState, GridIcon, GridLabelOverrides, HighlightingOptions, ColumnDefinition as CoreColumnDefinition, RowDragEndEvent, RowLoadingOptions } from "@gp-grid/core";
import { useGridState } from "./gridState";
import { useInputHandler } from "./composables/useInputHandler";
import { useFillHandle } from "./composables/useFillHandle";
import { useColumnSchemaSync } from "./composables/useColumnSchemaSync";
import type { ColumnDefinition, Row, VueCellRenderer, VueEditRenderer, VueHeaderRenderer, VueHeaderRendererRegistry } from "./types";
import FilterPopup from "./components/FilterPopup.vue";
import GridHeader from "./components/GridHeader.vue";
import GridBody from "./components/GridBody.vue";
import CellPeek from "./components/CellPeek.vue";

const props = withDefaults(
  defineProps<{
    columns: ColumnDefinition[];
    /** Controlled per-column state; applied through the core whenever it changes. */
    columnState?: ColumnStateUpdate[];
    dataSource?: DataSource<Row>;
    rowData?: Row[];
    rowHeight: number;
    /** Header height in pixels, the default height of every band. Default: rowHeight */
    headerHeight?: number;
    /** Height of each header band, indexed by band; a band without one is `headerHeight`. Changeable at runtime. */
    headerBandHeights?: readonly number[];
    /**
     * Nested header groups over the column ids; every column is referenced
     * once, ungrouped ones at the root. Applied together with `columns`.
     */
    columnGroups?: readonly ColumnGroupChild[];
    /** Budgets of `columnGroups`. Read at creation. */
    columnGroupLimits?: ColumnGroupLimits;
    /** Called when a column change is rejected; the previous schema stays. */
    onColumnSchemaRejected?: (error: ColumnSchemaError) => void;
    overscan?: number;
    /** Column overscan in CSS px per side for the mounted center window. */
    columnOverscan?: number;
    /** Displayed-width policy: "fit" (default) expands columns to the viewport. */
    columnLayout?: ColumnLayoutMode;
    rowLoading?: RowLoadingOptions;
    /**
     * Number of leading displayed rows kept visible below the header. Applied
     * at runtime; a new identity never rebuilds the core.
     */
    freezeRows?: FreezeRowsOptions;
    /** Called when the effective frozen count or its limiting reason changes. */
    onFrozenRowsChanged?: (state: FrozenRowsState) => void;
    sortingEnabled?: boolean;
    darkMode?: boolean;
    wheelDampening?: number;
    /** Max accumulated touch-fling velocity (logical px/ms) when scroll virtualization is active. Pair higher values with overscan 10-12. Default: 20 × rowHeight (~20,000 rows/s) */
    maxFlingVelocity?: number;
    cellRenderers?: Record<string, VueCellRenderer>;
    editRenderers?: Record<string, VueEditRenderer>;
    /** Header renderer registry, keyed by a column's or a group's `headerRenderer`. */
    headerRenderers?: VueHeaderRendererRegistry;
    cellRenderer?: VueCellRenderer;
    editRenderer?: VueEditRenderer;
    headerRenderer?: VueHeaderRenderer;
    /** SVG used by the default header's pin toggle. */
    pinIcon?: GridIcon;
    /** Initial viewport width for SSR (pixels). ResizeObserver takes over on client. */
    initialWidth?: number;
    /** Initial viewport height for SSR (pixels). ResizeObserver takes over on client. */
    initialHeight?: number;
    /** Row/column/cell highlighting configuration */
    highlighting?: HighlightingOptions<Row>;
    /** Function to extract unique ID from row. Required when onCellValueChanged is provided. */
    getRowId?: (row: Row) => RowId;
    /** Called when a cell value is changed via editing, fill drag, or paste. Requires getRowId. */
    onCellValueChanged?: (event: CellValueChangedEvent<Row>) => void;
    /** Called when a write is refused because the bound source is read-only. */
    onWriteRejected?: (event: CellWriteRejectedEvent) => void;
    /** Custom loading component to render instead of default spinner */
    loadingComponent?: Component<{ isLoading: boolean }>;
    /** Whether clicking and dragging any cell in a row drags the entire row. Default: false */
    rowDragEntireRow?: boolean;
    /** Called when a row is dropped after dragging. Consumer handles data reordering. */
    onRowDragEnd?: (event: RowDragEndEvent) => void;
    /** Called when a column is resized. */
    onColumnResized?: (event: ColumnResizedEvent) => void;
    /**
     * Whether the user can resize rows: every cell renders the row edge handle,
     * and Alt+ArrowUp/Down and Alt+Shift+Enter act. Changeable at runtime.
     * Default: false
     */
    rowResize?: boolean;
    /** Called per row resized by a drag, a key or a fit. */
    onRowResized?: (event: RowResizedEvent) => void;
    /** Clamps for the fit commands and the row resize gesture. Read at creation. */
    autoFit?: AutoFitOptions;
    /** Called when a column is moved/reordered. */
    onColumnMoved?: (event: ColumnMovedEvent) => void;
    /** Called when a column is pinned or unpinned. */
    onColumnPinned?: (event: ColumnPinnedEvent) => void;
    /** Override any user-visible grid label. Unspecified labels fall back to English defaults. */
    labels?: GridLabelOverrides;
  }>(),
  {
    overscan: 3,
    sortingEnabled: true,
    darkMode: false,
    wheelDampening: 0.1,
    rowResize: false,
    cellRenderers: () => ({}),
    editRenderers: () => ({}),
    headerRenderers: () => ({}),
    pinIcon: () => defaultPinIcon,
  },
);

// Refs
const outerContainerRef = ref<HTMLDivElement | null>(null);
const gridBodyComp = ref<InstanceType<typeof GridBody> | null>(null);
const bodyContainerRef = computed(() => gridBodyComp.value?.bodyRef ?? null);
const coreRef = shallowRef<GridCore<Row> | null>(null);
const currentDataSourceRef = shallowRef<DataSource<Row> | null>(null);
const coreUnsubscribeRef = shallowRef<(() => void) | null>(null);

// Synthetic touch scrolling for scaled grids: when scroll virtualization
// compresses the DOM scroll space, the controller takes over touch gestures
// so content tracks the finger 1:1 with a consistent fling. Inert otherwise.
const touchScroll = new TouchScrollController<Row>({
  getCore: () => coreRef.value,
  getScrollEl: () => bodyContainerRef.value,
  isBrowser: typeof window !== "undefined",
});

// Header scroll sync
const scrollLeft = ref(0);

// Inline direction, resampled on mount and on every container resize.
const rtl = ref(false);

// State
const pendingScroll = new PendingScrollLatch();
const { state, renderToken, contentToken, applyInstructions, reset: resetState } = useGridState({
  initialWidth: props.initialWidth,
  initialHeight: props.initialHeight,
  initialColumns: props.columns as unknown as CoreColumnDefinition[],
  initialColumnLayout: props.columnLayout ?? "fit",
  initialHeaderHeight: props.headerHeight ?? props.rowHeight,
  initialHeaderBandHeights: props.headerBandHeights,
  initialColumnGroups: props.columnGroups,
});

// Computed values
const totalHeaderHeight = computed(() => state.value.headerBands.totalHeight);
const resolvedLabels = computed(() => resolveGridLabels(props.labels));

// Resolved layout owned by the core. The `columns` prop is schema input only;
// the wrapper never renders it directly after mount.
const effectiveColumns = computed<CoreColumnDefinition[]>(
  () => state.value.columns,
);

// Displayed geometry: the core resolves offsets/widths and publishes them.
const columnWindow = computed(() => state.value.columnWindow);
const displayedColumnCount = computed(() => state.value.layout?.columns.length ?? 0);
const totalWidth = computed(() => state.value.contentWidth);
const slotsArray = computed(() => Array.from(state.value.slots.values()));

// Displayed index per column id, for `aria-colindex`. Keyed on the layout
// computed, not on `state`: a new function per batch re-renders every row.
const layout = computed(() => state.value.layout);
const displayedIndexOf = computed(() => {
  const index = new Map<string, number>();
  layout.value?.columns.forEach((column, at) => index.set(column.columnId, at));
  return (columnId: string): number => index.get(columnId) ?? 0;
});

// Input handling
const {
  handleCellMouseDown,
  handleCellDoubleClick,
  handleFillHandleMouseDown,
  handleHeaderClick,
  handleHeaderMouseDown,
  handleHeaderResizeMouseDown,
  handleRowResizeMouseDown,
  handleResizeDoubleClick,
  handleKeyDown,
  handlePaste,
  handleWheel,
  dragState,
} = useInputHandler(coreRef, bodyContainerRef, effectiveColumns, {
  activeCell: computed(() => state.value.activeCell),
  selectionRange: computed(() => state.value.selectionRange),
  editingCell: computed(() => state.value.editingCell),
  filterPopupOpen: computed(() => state.value.filterPopup?.isOpen ?? false),
  onBeforeProgrammaticScroll: () => touchScroll.stop(),
  scrollByWheel: (domDy) => touchScroll.scrollByWheel(domDy),
});

// Fill handle position, resolved by core geometry in rows-wrapper space.
const { fillHandlePosition } = useFillHandle({
  coreRef,
  activeCell: computed(() => state.value.activeCell),
  selectionRange: computed(() => state.value.selectionRange),
  slots: computed(() => state.value.slots),
  geometryRevision: computed(() => state.value.geometryRevision),
});

// Handle scroll
function handleScroll(): void {
  const container = bodyContainerRef.value;
  const core = coreRef.value;
  if (!container || !core) return;

  core.setViewport(
    container.scrollTop,
    toInlineX(container.scrollLeft, rtl.value),
    container.clientWidth,
    container.clientHeight,
  );
}

// Handle scroll with header sync
function handleScrollWithHeaderSync(): void {
  const container = bodyContainerRef.value;
  if (container) {
    // The header strip undoes the native scroll, so it takes the DOM value.
    scrollLeft.value = container.scrollLeft;
  }
  handleScroll();
}

// Handle filter apply
function handleFilterApply(colId: string, filter: ColumnFilterModel | null): void {
  const core = coreRef.value;
  if (core) {
    core.sortFilter.setFilter(colId, filter);
  }
}

// Handle filter popup close
function handleFilterPopupClose(): void {
  const core = coreRef.value;
  if (core) {
    core.sortFilter.closeFilterPopup();
  }
}

// Handle peek overlay close
function handlePeekClose(): void {
  coreRef.value?.edit.stopPeek();
}

// Resolve peek column + row data from current state
const peekContext = computed(() => {
  const peek = state.value.peekCell;
  if (!peek) return null;
  const column = effectiveColumns.value[peek.col];
  const slot = slotsArray.value.find((s) => s.rowIndex === peek.row);
  if (!column || !slot) return null;
  return { peek, column, rowData: slot.rowData as Row | undefined };
});

// Handle cell mouse enter (for highlighting)
function handleCellMouseEnter(rowIndex: number, colIndex: number): void {
  coreRef.value?.input.handleCellMouseEnter(rowIndex, colIndex);
}

// Handle cell mouse leave (for highlighting)
function handleCellMouseLeave(): void {
  coreRef.value?.input.handleCellMouseLeave();
}

// Helper to create or get data source
function getOrCreateDataSource(): DataSource<Row> {
  return props.dataSource ??
    (props.rowData ? createDataSourceFromArray(props.rowData) : createClientDataSource<Row>([]));
}

/**
 * Initialize or reinitialize the GridCore with a data source.
 * Handles cleanup of old core and subscription before creating new ones.
 */
function initializeCore(dataSource: DataSource<Row>): void {
  // Cleanup old subscription
  if (coreUnsubscribeRef.value) {
    coreUnsubscribeRef.value();
    coreUnsubscribeRef.value = null;
  }

  // Destroy old core (idempotent - safe if already destroyed)
  if (coreRef.value) {
    coreRef.value.destroy();
  }

  // Create new GridCore.
  // Vue's ColumnDefinition widens the renderer fields to also accept Components,
  // which core's agnostic type doesn't name. The cast is safe because core only
  // stores the renderer and never invokes it — the Vue layer handles dispatch.
  const core = new GridCore<Row>({
    columns: props.columns as unknown as CoreColumnDefinition[],
    columnGroups: props.columnGroups,
    columnGroupLimits: props.columnGroupLimits,
    onColumnSchemaRejected: (error) => props.onColumnSchemaRejected?.(error),
    dataSource,
    rowHeight: props.rowHeight,
    headerHeight: props.headerHeight ?? props.rowHeight,
    headerBandHeights: props.headerBandHeights,
    overscan: props.overscan,
    columnOverscan: props.columnOverscan,
    columnLayout: props.columnLayout ?? "fit",
    maxFlingVelocity: props.maxFlingVelocity,
    rowLoading: props.rowLoading,
    freezeRows: props.freezeRows,
    rowResize: props.rowResize,
    autoFit: props.autoFit,
    // Created on mount only, so a server render never builds a host.
    measurementHost: createDomMeasurementHost(() => outerContainerRef.value),
    sortingEnabled: props.sortingEnabled,
    highlighting: props.highlighting,
    getRowId: props.getRowId,
    onCellValueChanged: props.onCellValueChanged
      ? (event) => props.onCellValueChanged?.(event)
      : undefined,
    onWriteRejected: (event) => props.onWriteRejected?.(event),
    rowDragEntireRow: props.rowDragEntireRow ?? false,
    onRowDragEnd: (event) => props.onRowDragEnd?.(event),
    onColumnResized: (event) => props.onColumnResized?.(event),
    onRowResized: (event) => props.onRowResized?.(event),
    onColumnMoved: (event) => props.onColumnMoved?.(event),
    onColumnPinned: (event) => props.onColumnPinned?.(event),
    onFrozenRowsChanged: (state) => props.onFrozenRowsChanged?.(state),
    labels: props.labels,
  });

  // The columnState watcher only fires on change; apply the current value here.
  if (props.columnState) core.columns.setState(props.columnState);
  coreRef.value = core;
  touchScroll.syncCore();

  // Subscribe to batched instructions
  pendingScroll.clear();
  coreUnsubscribeRef.value = core.onBatchInstruction((instructions) => {
    pendingScroll.collect(instructions);
    applyInstructions(instructions);
  });

  // Initialize and set viewport
  core.initialize();

  const container = bodyContainerRef.value;
  if (container) {
    rtl.value = readIsRtl(container);
    core.setViewport(
      container.scrollTop,
      toInlineX(container.scrollLeft, rtl.value),
      container.clientWidth,
      container.clientHeight,
    );
  }
}

// Initialize on mount
onMounted(() => {
  const dataSource = getOrCreateDataSource();
  currentDataSourceRef.value = dataSource;

  initializeCore(dataSource);

  touchScroll.attach();

  // Set up ResizeObserver (only once, not per-core)
  const container = bodyContainerRef.value;
  if (container && typeof ResizeObserver !== "undefined") {
    const resizeObserver = new ResizeObserver(() => {
      // Use current core ref (may change during lifecycle)
      rtl.value = readIsRtl(container);
      touchScroll.resetDirection();
      coreRef.value?.setViewport(
        container.scrollTop,
        toInlineX(container.scrollLeft, rtl.value),
        container.clientWidth,
        container.clientHeight,
      );
    });
    resizeObserver.observe(container);

    onUnmounted(() => {
      resizeObserver.disconnect();
    });
  }

  // Cleanup on unmount
  onUnmounted(() => {
    touchScroll.detach();
    if (coreUnsubscribeRef.value) {
      coreUnsubscribeRef.value();
      coreUnsubscribeRef.value = null;
    }
    if (coreRef.value) {
      coreRef.value.destroy();
      coreRef.value = null;
    }
    if (currentDataSourceRef.value) {
      currentDataSourceRef.value.destroy?.();
      currentDataSourceRef.value = null;
    }
  });
});

// Watch for data source changes - swap via setDataSource to preserve grid state
watch(
  [() => props.dataSource, () => props.rowData],
  () => {
    // Dev warning: rowData prop changed with large dataset
    if (props.rowData && props.rowData.length > 10_000 && currentDataSourceRef.value) {
      console.warn(
        `[gp-grid] rowData prop changed with ${props.rowData.length} rows — this triggers a full rebuild. Use useGridData() for efficient updates.`,
      );
    }

    const newDataSource = getOrCreateDataSource();
    const oldDataSource = currentDataSourceRef.value;

    if (oldDataSource && oldDataSource !== newDataSource) {
      // Destroy old data source (terminates Web Workers)
      oldDataSource.destroy?.();
      // Update data source ref
      currentDataSourceRef.value = newDataSource;
      // Swap data source without destroying core (preserves sort, filter, scroll, selection)
      coreRef.value?.setDataSource(newDataSource);
    } else if (!oldDataSource) {
      // First time setting data source after mount
      currentDataSourceRef.value = newDataSource;
    }
  },
);

// Subscribe to data source changes
watch(
  () => props.dataSource,
  (dataSource) => {
    if (dataSource) {
      const mutableDataSource = dataSource as {
        subscribe?: (listener: () => void) => () => void;
      };
      if (mutableDataSource.subscribe) {
        const unsubscribe = mutableDataSource.subscribe(() => {
          coreRef.value?.refreshFromTransaction();
        });
        onUnmounted(() => unsubscribe());
      }
    }
  },
  { immediate: true },
);

// Apply programmatic scroll from SCROLL_TO. flush: 'post' ensures the DOM has
// been updated before the scroll positions are written.
watch(
  renderToken,
  () => {
    const pending = pendingScroll.take();
    const container = bodyContainerRef.value;
    if (pending === null || container === null) return;
    // A programmatic scroll wins over any in-flight synthetic fling.
    touchScroll.stop();
    if (pending.top !== null) container.scrollTop = pending.top;
    if (pending.left !== null) container.scrollLeft = toPhysicalX(pending.left, rtl.value);
  },
  { flush: "post" },
);

// Switch layout mode without recreating the core.
watch(
  () => props.columnLayout,
  (mode) => {
    coreRef.value?.columns.setLayout(mode ?? "fit");
  },
);

// Apply a new freeze configuration without recreating the core; the setter is
// silent for an equal request, and creation already received the prop.
watch(
  () => props.freezeRows,
  (config) => {
    coreRef.value?.frozenRows.set(config);
  },
);

watch(
  () => props.rowResize,
  (enabled) => {
    coreRef.value?.rowHeights.setResizable(enabled);
  },
);

// Watch for highlighting prop changes
watch(
  () => props.highlighting,
  (highlighting) => {
    if (coreRef.value?.highlight && highlighting) {
      coreRef.value.highlight.updateOptions(highlighting);
    }
  },
);

useColumnSchemaSync(coreRef, {
  columns: () => props.columns as unknown as CoreColumnDefinition[],
  columnGroups: () => props.columnGroups,
  headerBandHeights: () => props.headerBandHeights,
});

// Apply a controlled column-state input whenever it changes.
watch(
  () => props.columnState,
  (columnState) => {
    if (columnState) coreRef.value?.columns.setState(columnState);
  },
);

// Expose core for external access (e.g., via template ref)
defineExpose({
  core: coreRef,
});
</script>

<template>
  <div
    ref="outerContainerRef"
    :class="['gp-grid-container', { 'gp-grid-container--dark': darkMode }]"
    style="width: 100%; height: 100%; position: relative; display: flex; flex-direction: column"
    role="grid"
    :aria-colcount="displayedColumnCount"
    :aria-rowcount="state.totalRows + state.headerBands.count"
    :data-layout-revision="columnWindow?.layout.revision"
    tabindex="0"
    @keydown="handleKeyDown"
    @paste="handlePaste"
  >
    <GridHeader
      :header-bands="state.headerBands"
      :scroll-left="scrollLeft"
      :content-width="state.contentWidth"
      :total-width="totalWidth"
      :viewport-width="state.viewportWidth"
      :is-loading="state.isLoading"
      :column-window="columnWindow"
      :displayed-index-of="displayedIndexOf"
      :headers="state.headers"
      :sorting-enabled="sortingEnabled"
      :rtl="rtl"
      :labels="resolvedLabels"
      :on-header-mouse-down="handleHeaderMouseDown"
      :on-header-resize-mouse-down="handleHeaderResizeMouseDown"
      :on-resize-double-click="handleResizeDoubleClick"
      :core-ref="coreRef"
      :column-groups="columnGroups"
      :outer-container-ref="outerContainerRef"
      :header-renderers="headerRenderers ?? {}"
      :global-header-renderer="headerRenderer"
      :pin-icon="pinIcon"
    />

    <GridBody
      ref="gridBodyComp"
      :total-header-height="totalHeaderHeight"
      :header-row-count="state.headerBands.count"
      :content-width="state.contentWidth"
      :content-height="state.contentHeight"
      :total-width="totalWidth"
      :rows-wrapper-offset="state.rowsWrapperOffset"
      :row-regions="state.rowRegions"
      :announcement="state.announcement"
      :active-cell="state.activeCell"
      :selection-range="state.selectionRange"
      :editing-cell="state.editingCell"
      :hover-position="state.hoverPosition"
      :error="state.error"
      :is-loading="state.isLoading"
      :total-rows="state.totalRows"
      :labels="resolvedLabels"
      :slots-array="slotsArray"
      :column-window="columnWindow"
      :displayed-index-of="displayedIndexOf"
      :render-token="contentToken"
      :fill-handle-position="fillHandlePosition"
      :drag-state="dragState"
      :on-scroll="handleScrollWithHeaderSync"
      :on-wheel="handleWheel"
      :wheel-dampening="wheelDampening"
      :on-cell-mouse-down="handleCellMouseDown"
      :on-cell-double-click="handleCellDoubleClick"
      :on-cell-mouse-enter="handleCellMouseEnter"
      :on-cell-mouse-leave="handleCellMouseLeave"
      :on-fill-handle-mouse-down="handleFillHandleMouseDown"
      :on-row-resize-pointer-down="handleRowResizeMouseDown"
      :on-resize-double-click="handleResizeDoubleClick"
      :row-resize="rowResize"
      :core-ref="coreRef"
      :cell-renderers="cellRenderers ?? {}"
      :edit-renderers="editRenderers ?? {}"
      :global-cell-renderer="cellRenderer"
      :global-edit-renderer="editRenderer"
    />

  <!-- Loading overlay - positioned outside scrollable area to avoid Firefox sticky issues -->
  <div
    v-if="state.isLoading"
    :style="{
      position: 'absolute',
      top: `${totalHeaderHeight}px`,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 50,
      pointerEvents: 'none',
    }"
  >
    <div class="gp-grid-loading-overlay" />
    <component
      v-if="props.loadingComponent"
      :is="props.loadingComponent"
      :is-loading="true"
    />
    <div
      v-else
      class="gp-grid-loading"
    >
      <div class="gp-grid-loading-spinner" />
    </div>
  </div>

  <!-- Filter Popup -->
    <FilterPopup
      v-if="state.filterPopup?.isOpen && state.filterPopup.column"
      :column="state.filterPopup.column"
      :col-index="state.filterPopup.colIndex"
      :container-ref="outerContainerRef"
      :distinct-values="state.filterPopup.distinctValues"
      :current-filter="state.filterPopup.currentFilter"
      :labels="resolvedLabels"
      @apply="handleFilterApply"
      @close="handleFilterPopupClose"
    />

    <!-- Cell Peek (read-only multi-line overlay on dblclick of non-editable cell) -->
    <CellPeek
      v-if="peekContext"
      :peek-cell="peekContext.peek"
      :column="peekContext.column"
      :row-data="peekContext.rowData"
      :core="coreRef"
      :container-ref="bodyContainerRef"
      :cell-renderers="cellRenderers ?? {}"
      :global-cell-renderer="cellRenderer"
      @close="handlePeekClose"
    />

    <!-- Column resize line -->
    <div
      v-if="dragState.dragType === 'column-resize' && dragState.columnResize"
      class="gp-grid-column-resize-line"
      :style="{
        insetInlineStart: `${dragState.columnResize!.lineX}px`,
      }"
    />

    <!-- Row resize line: lineY is body-viewport space, so it sits below the header. -->
    <div
      v-if="dragState.dragType === 'row-resize' && dragState.rowResize"
      class="gp-grid-row-resize-line"
      :style="{
        top: `${totalHeaderHeight + dragState.rowResize!.lineY}px`,
      }"
    />

    <!-- Column move ghost -->
    <template v-if="dragState.dragType === 'column-move' && dragState.columnMove">
      <div
        class="gp-grid-column-move-ghost"
        :style="{
          left: `${dragState.columnMove!.currentX - dragState.columnMove!.ghostWidth / 2}px`,
          top: `${dragState.columnMove!.currentY - dragState.columnMove!.ghostHeight / 2}px`,
          width: `${dragState.columnMove!.ghostWidth}px`,
          height: `${dragState.columnMove!.ghostHeight}px`,
        }"
      >
        {{ effectiveColumns[dragState.columnMove!.sourceColIndex]?.headerName ?? effectiveColumns[dragState.columnMove!.sourceColIndex]?.field ?? '' }}
      </div>
      <div
        v-if="dragState.columnMove!.dropTargetIndex !== null"
        class="gp-grid-column-drop-indicator"
        :style="{
          insetInlineStart: `${dragState.columnMove.dropIndicatorX}px`,
          height: `${totalHeaderHeight}px`,
        }"
      />
    </template>

    <!-- Row drag ghost (fixed position, follows cursor) -->
    <div
      v-if="dragState.dragType === 'row-drag' && dragState.rowDrag"
      class="gp-grid-row-drag-ghost"
      :style="{
        left: `${dragState.rowDrag!.currentX + 12}px`,
        top: `${dragState.rowDrag!.currentY - dragState.rowDrag!.sourceRowHeight / 2}px`,
        width: `${Math.min(300, totalWidth)}px`,
        height: `${dragState.rowDrag!.sourceRowHeight}px`,
      }"
    />
  </div>
</template>

// packages/angular/src/lib/gp-grid.component.ts
import {
  Component,
  ElementRef,
  OnInit,
  AfterViewInit,
  OnDestroy,
  ViewChild,
  ChangeDetectionStrategy,
  PLATFORM_ID,
  inject,
  input,
  output,
  effect,
  computed,
} from '@angular/core';
import type {
  CellRendererTemplate,
  EditRendererTemplate,
  HeaderRendererRegistry,
  HeaderRendererTemplate,
  HeaderSortEvent,
} from './components';
import type {
  AngularColumnDefinition,
  AngularColumnGroupChild,
  GroupLabelRendererTemplate,
} from './types';
import { isPlatformBrowser } from '@angular/common';
import type {
  AutoFitOptions,
  CellValue,
  CellValueChangedEvent,
  CellWriteRejectedEvent,
  ColumnDefinition,
  ColumnFilterModel,
  ColumnGroupChild,
  ColumnGroupLimits,
  ColumnMovedEvent,
  ColumnLayoutMode,
  ColumnPin,
  ColumnPinnedEvent,
  ColumnResizedEvent,
  ColumnSchemaError,
  ColumnStateUpdate,
  DataSource,
  FreezeRowsOptions,
  FrozenRowsState,
  GridCore,
  GridIcon,
  GridLabelOverrides,
  HighlightingOptions,
  RowDragEndEvent,
  RowGrouping,
  RowGroupingRejection,
  RowGroupToggledEvent,
  RowLoadingOptions,
  RowId,
  RowResizedEvent,
  ResizeTarget,
} from '@gp-grid/core';
import { defaultPinIcon, resolveGridLabels, toInlineX } from '@gp-grid/core';
import {
  GridHeaderComponent,
  GridBodyComponent,
  GridOverlaysComponent,
  CellPeekComponent,
} from './components';
import type {
  HeaderPointerDownEvent,
  FilterPointerDownEvent,
  ResizePointerDownEvent,
  CellPointerDownEvent,
  CellPointerEnterEvent,
  CellDoubleClickEvent,
  FillHandlePointerDownEvent,
  RowResizePointerDownEvent,
} from './components';
import { GP_GRID_TEMPLATE } from './gp-grid.template';
import { GpGridViewModel } from './gp-grid-view-model';
import { GpGridBindings } from './gp-grid-bindings';
import { buildGridCore } from './gp-grid.factory';
import { createRowGroupCells } from './gp-grid-row-groups';

@Component({
  selector: 'gp-grid',
  standalone: true,
  imports: [GridHeaderComponent, GridBodyComponent, GridOverlaysComponent, CellPeekComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`:host { display: block; height: 100%; min-height: 0; }`],
  template: GP_GRID_TEMPLATE,
})
export class GpGridComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('container', { static: true }) container!: ElementRef<HTMLDivElement>;
  @ViewChild(GridBodyComponent) body!: GridBodyComponent;

  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  columns = input.required<AngularColumnDefinition[]>();
  /** Controlled per-column state; applied through the core whenever it changes. */
  columnState = input<ColumnStateUpdate[] | null | undefined>(null);
  rows = input<unknown[]>([]);
  dataSource = input<DataSource<unknown> | null>(null);
  getRowId = input<((row: unknown) => RowId) | null>(null);
  rowHeight = input<number>(32);
  headerHeight = input<number>(32);
  /** Height of each header band, indexed by band; a band without one is `headerHeight`. Changeable at runtime. */
  headerBandHeights = input<readonly number[] | undefined>(undefined);
  /**
   * Nested header groups over the column ids; every column is referenced
   * once, ungrouped ones at the root. Applied together with `columns`.
   */
  columnGroups = input<readonly AngularColumnGroupChild[] | undefined>(undefined);
  /** Budgets of `columnGroups`. Creation-only. */
  columnGroupLimits = input<ColumnGroupLimits | undefined>(undefined);
  darkMode = input<boolean>(false);
  cellRenderers = input<Record<string, CellRendererTemplate>>({});
  /** Header renderer registry, keyed by a column's or a group's `headerRenderer`. */
  headerRenderers = input<HeaderRendererRegistry>({});
  editRenderers = input<Record<string, EditRendererTemplate>>({});
  cellRenderer = input<CellRendererTemplate | null>(null);
  headerRenderer = input<HeaderRendererTemplate | null>(null);
  /** SVG used by the default header's pin toggle. */
  pinIcon = input<GridIcon>(defaultPinIcon);
  editRenderer = input<EditRendererTemplate | null>(null);
  highlighting = input<HighlightingOptions | null>(null);
  rowDragEntireRow = input<boolean>(false);
  overscan = input<number>(3);
  /** Column overscan in CSS px per side for the mounted center window. */
  columnOverscan = input<number | undefined>(undefined);
  /** Frozen prefix configuration; applied at runtime without recreating the core. */
  freezeRows = input<FreezeRowsOptions | undefined>(undefined);
  /** Displayed-width policy: "fit" (default) expands columns to the viewport. */
  columnLayout = input<ColumnLayoutMode>('fit');
  /** Max accumulated touch-fling velocity (logical px/ms) when scroll virtualization is active. Pair higher values with overscan 10-12. */
  maxFlingVelocity = input<number | undefined>(undefined);
  rowLoading = input<RowLoadingOptions | null>(null);
  sortingEnabled = input<boolean>(true);
  wheelDampening = input<number>(0.1);
  /**
   * Whether the user can resize rows: every cell renders the row edge handle,
   * and Alt+ArrowUp/Down and Alt+Shift+Enter act. Changeable at runtime.
   */
  rowResize = input<boolean>(false);
  /** Bounds of the fit commands and the row resize gestures; read at creation. */
  autoFit = input<AutoFitOptions | undefined>(undefined);
  onRowDragEnd = output<RowDragEndEvent>();
  onCellValueChanged = output<CellValueChangedEvent<unknown>>();
  onWriteRejected = output<CellWriteRejectedEvent>();
  onColumnResized = output<ColumnResizedEvent>();
  onRowResized = output<RowResizedEvent>();
  onColumnMoved = output<ColumnMovedEvent>();
  onColumnPinned = output<ColumnPinnedEvent>();
  /** C9: fires on a published change of the effective frozen count or its limit. */
  onFrozenRowsChanged = output<FrozenRowsState>();
  /** Fires when a column change is rejected; the previous schema stays. */
  onColumnSchemaRejected = output<ColumnSchemaError>();
  /** Groups the resident rows; a new value regroups without recreating the core. */
  rowGrouping = input<RowGrouping | null | undefined>(undefined);
  /** Column showing a group's expander and label; the first displayed column when absent or hidden. */
  groupLabelColumn = input<string | undefined>(undefined);
  /** Renders the label of a group or total row. */
  groupLabelRenderer = input<GroupLabelRendererTemplate | null>(null);
  /** Fires per group a pointer or key gesture toggled; commands stay silent. */
  onRowGroupToggled = output<RowGroupToggledEvent>();
  /** Fires when `rowGrouping` cannot apply to the bound source; the grid keeps the source's rows. */
  onRowGroupingRejected = output<RowGroupingRejection>();
  labels = input<GridLabelOverrides>({});

  protected readonly resolvedLabels = computed(() => resolveGridLabels(this.labels()));

  /** Rendered on the root; a fit measured under another revision is stale. */
  protected readonly layoutRevision = computed(() => this.vm.columnWindow()?.layout.revision ?? null);

  // Assigned once `bindings` exists; the view model must not reference it
  // directly or the two initializers would form a type cycle.
  private readonly boundCore: { current: GridCore<unknown> | null } = { current: null };

  protected readonly vm = new GpGridViewModel({
    getRows: () => this.rows(),
    getCore: () => this.boundCore.current,
  });

  private readonly bindings = new GpGridBindings<unknown>({
    vm: this.vm,
    isBrowser: this.isBrowser,
    getContainer: () => this.container?.nativeElement ?? null,
    getBody: () => this.body?.scrollContainer?.nativeElement ?? null,
  });

  protected readonly rowGroupCells = createRowGroupCells({
    hierarchical: this.vm.hierarchical,
    layout: this.vm.layout,
    columns: this.vm.effectiveColumns,
    labels: this.resolvedLabels,
    groupLabelColumn: this.groupLabelColumn,
    groupLabelRenderer: this.groupLabelRenderer,
    onTogglePointerDown: (rowIndex, event) => this.bindings.input.groupTogglePointerDown(rowIndex, event),
    onToggle: (rowIndex) => this.bindings.coreRef?.input.handleGroupToggle(rowIndex),
  });

  // The Angular group type differs from core's only by its template renderer.
  private readonly coreColumnGroups = computed(
    () => this.columnGroups() as readonly ColumnGroupChild[] | undefined,
  );

  constructor() {
    effect(() => this.bindings.applyPendingScroll(), { allowSignalWrites: true });
    effect(() => this.bindings.syncHighlighting(this.highlighting()));
    effect(
      () => this.bindings.syncColumns(this.columns() as unknown as ColumnDefinition[], this.coreColumnGroups()),
      { allowSignalWrites: true },
    );
    effect(() => this.bindings.syncHeaderBandHeights(this.headerBandHeights()), { allowSignalWrites: true });
    effect(() => this.bindings.syncColumnState(this.columnState() ?? []), { allowSignalWrites: true });
    effect(() => this.bindings.syncRows(this.rows(), this.dataSource()), { allowSignalWrites: true });
    effect(() => this.bindings.syncColumnLayout(this.columnLayout()), { allowSignalWrites: true });
    effect(() => this.bindings.syncFreezeRows(this.freezeRows()), { allowSignalWrites: true });
    effect(() => this.bindings.syncRowResize(this.rowResize()));
    effect(() => this.bindings.syncRowGrouping(this.rowGrouping()), { allowSignalWrites: true });
  }

  ngOnInit(): void {
    const columns = this.columns() as unknown as ColumnDefinition[];
    const dataSource = this.bindings.dataSourceOwner.initialize(this.dataSource(), this.rows());
    this.bindings.syncRowGrouping(this.rowGrouping());
    const core = buildGridCore<unknown>(
      {
        columns,
        columnGroups: this.coreColumnGroups(),
        columnGroupLimits: this.columnGroupLimits(),
        dataSource,
        rowHeight: this.rowHeight(),
        headerHeight: this.headerHeight(),
        headerBandHeights: this.headerBandHeights(),
        overscan: this.overscan(),
        columnOverscan: this.columnOverscan(),
        freezeRows: this.freezeRows(),
        columnLayout: this.columnLayout(),
        maxFlingVelocity: this.maxFlingVelocity(),
        rowLoading: this.rowLoading() ?? undefined,
        sortingEnabled: this.sortingEnabled(),
        highlighting: (this.highlighting() ?? undefined) as HighlightingOptions<unknown> | undefined,
        getRowId: this.getRowId() ?? undefined,
        rowDragEntireRow: this.rowDragEntireRow(),
        labels: this.labels(),
        rowResize: this.rowResize(),
        autoFit: this.autoFit(),
        rowGrouping: this.rowGrouping(),
        measureRoot: this.isBrowser ? () => this.container?.nativeElement ?? null : null,
      },
      {
        onRowDragEnd: (event) => this.onRowDragEnd.emit(event),
        onCellValueChanged: (event) => this.onCellValueChanged.emit(event),
        onWriteRejected: (event) => this.onWriteRejected.emit(event),
        onColumnResized: (event) => this.onColumnResized.emit(event),
        onRowResized: (event) => this.onRowResized.emit(event),
        onColumnMoved: (event) => this.onColumnMoved.emit(event),
        onColumnPinned: (event) => this.onColumnPinned.emit(event),
        onFrozenRowsChanged: (state) => this.onFrozenRowsChanged.emit(state),
        onColumnSchemaRejected: (error) => this.onColumnSchemaRejected.emit(error),
        onRowGroupToggled: (event) => this.onRowGroupToggled.emit(event),
        onRowGroupingRejected: (rejection) => this.onRowGroupingRejected.emit(rejection),
      },
    );
    this.vm.seedHeaderBands({
      initialColumns: columns,
      initialColumnLayout: this.columnLayout(),
      initialHeaderHeight: this.headerHeight(),
      initialHeaderBandHeights: this.headerBandHeights(),
      initialColumnGroups: this.coreColumnGroups(),
    });
    this.boundCore.current = core;
    this.bindings.attach(core, dataSource);
    // The columnState effect ran before the core existed; apply it now.
    this.bindings.syncColumnState(this.columnState() ?? []);
  }

  ngAfterViewInit(): void {
    if (this.isBrowser === false) return;
    this.bindings.observeViewport(this.body.scrollContainer.nativeElement);
    document.addEventListener('pointermove', this.onDocumentPointerMove, { passive: false });
    document.addEventListener('pointerup', this.onDocumentPointerUp);
  }

  ngOnDestroy(): void {
    this.boundCore.current = null;
    this.bindings.destroy();
    if (this.isBrowser) {
      document.removeEventListener('pointermove', this.onDocumentPointerMove);
      document.removeEventListener('pointerup', this.onDocumentPointerUp);
    }
  }

  /**
   * The underlying core instance, mirroring the `core` exposed by the React
   * and Vue wrappers. Use it to read values or refresh after a columnar source
   * adopts a new revision.
   */
  get core(): GridCore<unknown> | null {
    return this.bindings.coreRef;
  }

  /** Body scroll element, provided to overlays that need its screen origin. */
  protected get bodyScrollContainer(): HTMLElement | null {
    return this.body?.scrollContainer?.nativeElement ?? null;
  }

  protected onBodyScroll(scrollLeft: number): void {
    const el = this.body.scrollContainer.nativeElement;
    const logicalScrollLeft = toInlineX(scrollLeft, this.bindings.isRtl);
    // The header strip undoes the native scroll, so it takes the DOM value.
    this.vm.scrollLeft.set(scrollLeft);
    this.bindings.coreRef?.setViewport(
      el.scrollTop,
      logicalScrollLeft,
      el.clientWidth,
      el.clientHeight,
    );
  }

  protected onHeaderPointerDown(evt: HeaderPointerDownEvent): void {
    if (this.bindings.input.headerPointerDown(evt.colIndex, evt.colWidth, evt.colHeight, evt.event)) {
      evt.event.preventDefault();
    }
  }

  protected onFilterPointerDown(evt: FilterPointerDownEvent): void {
    this.vm.setFilterAnchor(evt.anchorEl);
    const rect = evt.anchorEl.getBoundingClientRect();
    this.bindings.coreRef?.sortFilter.openFilterPopup(evt.colIndex, {
      top: rect.top,
      left: rect.left,
      width: rect.width,
      height: rect.height,
    });
  }

  protected onCellPointerDown(evt: CellPointerDownEvent): void {
    const action = this.bindings.input.cellPointerDown(evt.rowIndex, evt.colIndex, evt.event);
    if (action.preventDefault) evt.event.preventDefault();
    if (action.focusContainer) {
      this.container.nativeElement.focus({ preventScroll: true });
    }
  }

  protected onCellPointerEnter(evt: CellPointerEnterEvent): void {
    this.bindings.input.cellPointerEnter(evt.rowIndex, evt.colIndex);
  }

  protected onFillHandlePointerDown(evt: FillHandlePointerDownEvent): void {
    const action = this.bindings.input.fillHandlePointerDown(
      this.vm.activeCell(),
      this.vm.selectionRange(),
      evt.event,
    );
    if (action.preventDefault) evt.event.preventDefault();
    if (action.stopPropagation) evt.event.stopPropagation();
  }

  protected onCellPointerLeave(): void {
    this.bindings.input.cellPointerLeave();
  }

  protected computeRowClassesFn = (rowIndex: number, rowData: unknown): string[] => {
    return this.bindings.coreRef?.highlight?.computeRowClasses(rowIndex, rowData) ?? [];
  };

  /** Raw value reader shared with the body and peek: record-less rows work. */
  protected readCellValueFn = (rowIndex: number, colIndex: number): CellValue =>
    this.bindings.coreRef?.cells.getValue(rowIndex, colIndex) ?? null;

  protected readFieldValueFn = (rowIndex: number, field: string): CellValue =>
    this.bindings.coreRef?.cells.getFieldValue(rowIndex, field) ?? null;

  protected readRowIdFn = (rowIndex: number): RowId | undefined =>
    this.bindings.coreRef?.rows.getId(rowIndex);

  protected computeCellClassesFn = (
    rowIndex: number,
    colIndex: number,
    column: ColumnDefinition,
    rowData: unknown,
  ): string[] => {
    return this.bindings.coreRef?.highlight?.computeCombinedCellClasses(
      rowIndex,
      colIndex,
      column,
      rowData,
    ) ?? [];
  };

  protected onCellDoubleClick(evt: CellDoubleClickEvent): void {
    this.bindings.coreRef?.input.handleCellDoubleClick(evt.rowIndex, evt.colIndex);
  }

  protected onPeekClose(): void {
    this.bindings.coreRef?.edit.stopPeek();
  }

  protected peekContext = computed(() => {
    const peek = this.vm.peekCell();
    if (peek === null) return null;
    const column = this.vm.effectiveColumns()[peek.col];
    if (!column) return null;
    const slot = [...this.vm.slots().values()].find((s) => s.rowIndex === peek.row);
    if (!slot) return null;
    return { peek, column, rowData: slot.rowData };
  });

  protected onEditValueChange(value: string): void {
    this.bindings.coreRef?.edit.updateValue(value, this.vm.editingCell()?.editId);
  }

  protected onEditCommit(): void {
    this.bindings.coreRef?.edit.commit(this.vm.editingCell()?.editId);
  }

  protected onEditCancel(): void {
    this.bindings.coreRef?.edit.cancel(this.vm.editingCell()?.editId);
  }

  protected onHeaderSort(evt: HeaderSortEvent): void {
    this.bindings.coreRef?.sortFilter.setSort(evt.colId, evt.direction, evt.addToExisting);
  }

  protected onHeaderPin(evt: { columnId: string; pinned: ColumnPin | null }): void {
    this.bindings.coreRef?.columns.setPinned(evt.columnId, evt.pinned);
  }

  protected onWheel(event: WheelEvent): void {
    const bodyEl = this.body?.scrollContainer?.nativeElement;
    if (!bodyEl) return;
    const dampened = this.bindings.input.wheel(event.deltaY, event.deltaX, this.wheelDampening());
    if (dampened) {
      event.preventDefault();
      if (this.bindings.touchScroll.scrollByWheel(dampened.dy) === false) bodyEl.scrollTop += dampened.dy;
      // Wheel deltaX is physical, unlike the inline-relative deltas core emits.
      bodyEl.scrollLeft += dampened.dx;
    }
  }

  protected onKeyDown(event: KeyboardEvent): void {
    const editing = this.vm.editingCell();
    const result = this.bindings.input.keyDown(
      event,
      this.vm.activeCell(),
      editing === null ? null : { row: editing.row, col: editing.col },
      this.vm.filterPopup() !== null,
    );
    if (result.preventDefault) event.preventDefault();
    if (result.scrollToCell) this.bindings.scrollToCell(result.scrollToCell);
  }

  protected onPaste(event: ClipboardEvent): void {
    const editing = this.vm.editingCell();
    const handled = this.bindings.input.pasteText(
      event.clipboardData?.getData('text/plain') ?? '',
      editing === null ? null : { row: editing.row, col: editing.col },
      this.vm.filterPopup() !== null,
    );
    if (handled) event.preventDefault();
  }

  protected onResizePointerDown(evt: ResizePointerDownEvent): void {
    if (this.bindings.input.resizePointerDown(evt.colIndex, evt.colWidth, evt.event)) {
      evt.event.preventDefault();
    }
  }

  protected onRowResizePointerDown(evt: RowResizePointerDownEvent): void {
    if (this.bindings.input.rowResizePointerDown(evt.rowIndex, evt.rowHeight, evt.event)) {
      evt.event.preventDefault();
    }
  }

  protected onResizeDoubleClick(target: ResizeTarget): void {
    this.bindings.input.resizeDoubleClick(target);
  }

  protected onFilterApply(event: { colId: string; filter: ColumnFilterModel | null }): void {
    this.bindings.coreRef?.sortFilter.setFilter(event.colId, event.filter);
    this.vm.filterPopup.set(null);
  }

  protected onFilterClose(): void {
    this.bindings.coreRef?.sortFilter.closeFilterPopup();
    this.vm.filterPopup.set(null);
  }

  private onDocumentPointerMove = (event: PointerEvent): void => {
    if (this.bindings.input.documentPointerMove(event)) event.preventDefault();
  };

  private onDocumentPointerUp = (_event: PointerEvent): void => {
    const { wasRowDrag } = this.bindings.input.documentPointerUp();
    if (wasRowDrag) this.bindings.pendingRowDrag.releaseLocks();
  };
}
