// packages/vue/src/components/CellPeek.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import type {
  CellPosition,
  CellValue,
  ColumnDefinition,
  GridCore,
} from "@gp-grid/core";
import { bindPeekSelectAll, fixedLeftForInline } from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import type { Row, VueCellRenderer } from "../types";

const props = defineProps<{
  peekCell: CellPosition;
  column: ColumnDefinition;
  /** Source record, or `undefined` for a record-less (columnar) row. */
  rowData: Row | undefined;
  /** Bound core, used to read raw values without materializing a record. */
  core: GridCore | null;
  containerRef: HTMLDivElement | null;
  cellRenderers: Record<string, VueCellRenderer>;
  globalCellRenderer?: VueCellRenderer;
}>();

const emit = defineEmits<{
  close: [];
}>();

const overlayRef = ref<HTMLDivElement | null>(null);
const top = ref(0);
const left = ref(0);
const width = ref(0);
const clipPath = ref("inset(0)");
const positioned = ref(false);

let rafId: number | null = null;

// The portal is position:fixed, so the cell's viewport-space bounds are
// offset by the body client area's screen origin.
const updatePosition = (): void => {
  const container = props.containerRef;
  const overlay = overlayRef.value;
  if (!container || !overlay) return;

  const bounds = props.core?.geometry.getCellBounds(
    props.peekCell.row,
    props.peekCell.col,
    "viewport",
  );
  if (bounds === undefined) {
    emit("close");
    return;
  }

  // Keep the cell's layout width so its content does not reflow, then clip
  // the portion covered by either pin region.
  const clip = props.core?.geometry.getColumnClip(props.peekCell.col);
  if (clip !== undefined && (bounds.left >= clip.end || bounds.left + bounds.width <= clip.start)) {
    emit("close");
    return;
  }
  const inlineStart = clip === undefined ? bounds.left : Math.max(bounds.left, clip.start);
  const inlineEnd = clip === undefined
    ? bounds.left + bounds.width
    : Math.min(bounds.left + bounds.width, clip.end);
  const clippedWidth = inlineEnd - inlineStart;
  const fullLeft = fixedLeftForInline(container, bounds.left, bounds.width);
  const clippedLeft = fixedLeftForInline(container, inlineStart, clippedWidth);
  const leftInset = Math.max(0, clippedLeft - fullLeft);
  const rightInset = Math.max(0, fullLeft + bounds.width - clippedLeft - clippedWidth);

  const origin = container.getBoundingClientRect();
  top.value = origin.top + bounds.top;
  left.value = fullLeft;
  width.value = bounds.width;
  clipPath.value = `inset(0 ${rightInset}px 0 ${leftInset}px)`;
  positioned.value = true;
};

const onScrollOrResize = (): void => {
  if (rafId !== null) return;
  rafId = requestAnimationFrame(() => {
    rafId = null;
    updatePosition();
  });
};

const onPointerDown = (e: PointerEvent): void => {
  const target = e.target as HTMLElement;
  if (overlayRef.value?.contains(target)) return;
  emit("close");
};


let pointerRafId: number | null = null;
let unbindSelectAll: (() => void) | null = null;

onMounted(() => {
  updatePosition();
  window.addEventListener("scroll", onScrollOrResize, { passive: true, capture: true });
  window.addEventListener("resize", onScrollOrResize);
  if (overlayRef.value) unbindSelectAll = bindPeekSelectAll(overlayRef.value);
  pointerRafId = requestAnimationFrame(() => {
    document.addEventListener("pointerdown", onPointerDown);
  });
});

onUnmounted(() => {
  window.removeEventListener("scroll", onScrollOrResize, { capture: true });
  window.removeEventListener("resize", onScrollOrResize);
  document.removeEventListener("pointerdown", onPointerDown);
  unbindSelectAll?.();
  if (rafId !== null) cancelAnimationFrame(rafId);
  if (pointerRafId !== null) cancelAnimationFrame(pointerRafId);
});

watch(
  () => [props.peekCell.row, props.peekCell.col, props.core?.geometry.revision ?? 0],
  () => updatePosition(),
  { flush: "post" },
);

const overlayStyle = computed(() => ({
  position: "fixed" as const,
  top: `${top.value}px`,
  left: `${left.value}px`,
  width: `${width.value}px`,
  clipPath: clipPath.value,
  visibility: positioned.value ? ("visible" as const) : ("hidden" as const),
}));

const peekVNode = computed(() => {
  const core = props.core;
  const getValue = (field: string): CellValue =>
    core?.getFieldValue(props.peekCell.row, field) ?? null;

  return renderCell({
    column: props.column,
    rowData: props.rowData,
    rawValue: core?.getCellValue(props.peekCell.row, props.peekCell.col) ?? null,
    rowId: core?.getRowId(props.peekCell.row),
    getValue,
    rowIndex: props.peekCell.row,
    colIndex: props.peekCell.col,
    isActive: true,
    isSelected: false,
    isEditing: false,
    cellRenderers: props.cellRenderers,
    globalCellRenderer: props.globalCellRenderer,
  });
});
</script>

<template>
  <div ref="overlayRef" class="gp-grid-cell-peek" :style="overlayStyle">
    <component :is="peekVNode" />
  </div>
</template>

// packages/angular/src/lib/components/cell-peek.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  OnDestroy,
  TemplateRef,
  ViewChild,
  computed,
  effect,
  input,
  output,
  signal,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  bindPeekSelectAll,
  fixedLeftForInline,
  formatCellValue,
  getFieldValue,
  type CellPosition,
  type CellRendererParams,
  type CellValue,
  type ColumnDefinition,
  type GridCore,
  type RowId,
} from '@gp-grid/core';
import type { CellRendererTemplate } from './grid-body.component';

const TEMPLATE = `
  <div
    #overlayEl
    class="gp-grid-cell-peek"
    [style.position]="'fixed'"
    [style.top.px]="top()"
    [style.left.px]="left()"
    [style.width.px]="width()"
    [style.clip-path]="clipPath()"
    [style.visibility]="positioned() ? 'visible' : 'hidden'">
    @if (template(); as tpl) {
      <ng-container
        [ngTemplateOutlet]="tpl"
        [ngTemplateOutletContext]="{ $implicit: rendererParams() }">
      </ng-container>
    } @else {
      {{ fallbackText() }}
    }
  </div>
`;

@Component({
  selector: 'gp-grid-cell-peek',
  standalone: true,
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: TEMPLATE,
})
export class CellPeekComponent implements AfterViewInit, OnDestroy {
  @ViewChild('overlayEl', { static: false }) overlayEl!: ElementRef<HTMLDivElement>;

  peekCell = input.required<CellPosition>();
  column = input.required<ColumnDefinition>();
  rowData = input.required<unknown>();
  readCellValue = input<((rowIndex: number, colIndex: number) => CellValue) | null>(null);
  readFieldValue = input<((rowIndex: number, field: string) => CellValue) | null>(null);
  readRowId = input<((rowIndex: number) => RowId | undefined) | null>(null);
  containerEl = input.required<HTMLElement | null>();
  /** Bound core; peek anchoring is a geometry query, not a DOM measurement. */
  core = input<GridCore<unknown> | null>(null);
  cellRenderers = input<Record<string, CellRendererTemplate>>({});
  globalCellRenderer = input<CellRendererTemplate | null>(null);

  close = output<void>();

  protected top = signal(0);
  protected left = signal(0);
  protected width = signal(0);
  protected clipPath = signal('inset(0)');
  protected positioned = signal(false);

  protected template = computed<CellRendererTemplate | null>(() => {
    const renderer: unknown = this.column().cellRenderer;
    if (renderer instanceof TemplateRef) return renderer as CellRendererTemplate;
    if (typeof renderer === 'string') {
      const registered = this.cellRenderers()[renderer];
      if (registered) return registered;
    }
    return this.globalCellRenderer();
  });

  private rawValueFor(col: ColumnDefinition): CellValue {
    const read = this.readCellValue();
    if (read) return read(this.peekCell().row, this.peekCell().col);
    return getFieldValue(this.rowData(), col.field);
  }

  protected rendererParams = computed<CellRendererParams>(() => {
    const col = this.column();
    const data = this.rowData();
    const rawValue = this.rawValueFor(col);
    const displayValue = col.valueFormatter ? col.valueFormatter(rawValue) : rawValue;
    const readField = this.readFieldValue();
    const rowIndex = this.peekCell().row;
    return {
      value: displayValue,
      rowData: data,
      rowId: this.readRowId()?.(rowIndex),
      columnId: col.colId ?? col.field,
      getValue: (field: string) => (readField ? readField(rowIndex, field) : null),
      column: col,
      rowIndex: this.peekCell().row,
      colIndex: this.peekCell().col,
      isActive: true,
      isSelected: false,
      isEditing: false,
    };
  });

  protected fallbackText = computed<string>(() => {
    const col = this.column();
    const renderer = col.cellRenderer;
    const value = this.rawValueFor(col);
    if (typeof renderer === 'function') {
      const result = renderer(this.rendererParams());
      return result === null || result === undefined ? '' : String(result);
    }
    return formatCellValue(value, col.valueFormatter);
  });

  private rafId: number | null = null;
  private pointerRafId: number | null = null;
  private unbindSelectAll: (() => void) | null = null;

  constructor() {
    effect(() => {
      this.peekCell();
      // Read the revision so a geometry change repositions the overlay.
      this.core()?.geometry.revision;
      this.updatePosition();
    });
  }

  ngAfterViewInit(): void {
    this.updatePosition();
    window.addEventListener('scroll', this.onWindowScrollOrResize, { passive: true, capture: true });
    window.addEventListener('resize', this.onWindowScrollOrResize);
    if (this.overlayEl?.nativeElement) {
      this.unbindSelectAll = bindPeekSelectAll(this.overlayEl.nativeElement);
    }
    this.pointerRafId = requestAnimationFrame(() => {
      document.addEventListener('pointerdown', this.onDocumentPointerDown);
    });
  }

  ngOnDestroy(): void {
    window.removeEventListener('scroll', this.onWindowScrollOrResize, { capture: true });
    window.removeEventListener('resize', this.onWindowScrollOrResize);
    document.removeEventListener('pointerdown', this.onDocumentPointerDown);
    this.unbindSelectAll?.();
    if (this.rafId !== null) cancelAnimationFrame(this.rafId);
    if (this.pointerRafId !== null) cancelAnimationFrame(this.pointerRafId);
  }

  @HostListener('keydown.escape')
  onEscape(): void {
    this.close.emit();
  }

  private updatePosition(): void {
    const container = this.containerEl();
    const overlay = this.overlayEl?.nativeElement;
    if (!container || !overlay) return;

    const peek = this.peekCell();
    const bounds = this.core()?.geometry.getCellBounds(peek.row, peek.col, "viewport");
    if (bounds === undefined) {
      this.close.emit();
      return;
    }

    // Keep the cell's layout width so its content does not reflow, then clip
    // the portion covered by either pin region.
    const clip = this.core()?.geometry.getColumnClip(peek.col);
    if (clip !== undefined && (bounds.left >= clip.end || bounds.left + bounds.width <= clip.start)) {
      this.close.emit();
      return;
    }
    const inlineStart = clip === undefined ? bounds.left : Math.max(bounds.left, clip.start);
    const inlineEnd = clip === undefined
      ? bounds.left + bounds.width
      : Math.min(bounds.left + bounds.width, clip.end);
    const clippedWidth = inlineEnd - inlineStart;
    const left = fixedLeftForInline(container, bounds.left, bounds.width);
    const clippedLeft = fixedLeftForInline(container, inlineStart, clippedWidth);
    const leftInset = Math.max(0, clippedLeft - left);
    const rightInset = Math.max(0, left + bounds.width - clippedLeft - clippedWidth);

    // The overlay is position:fixed, so the cell's viewport-space bounds are
    // offset by the body client area's screen origin.
    const origin = container.getBoundingClientRect();
    this.top.set(origin.top + bounds.top);
    this.left.set(left);
    this.width.set(bounds.width);
    this.clipPath.set(`inset(0 ${rightInset}px 0 ${leftInset}px)`);
    this.positioned.set(true);
  }

  private onWindowScrollOrResize = (): void => {
    if (this.rafId !== null) return;
    this.rafId = requestAnimationFrame(() => {
      this.rafId = null;
      this.updatePosition();
    });
  };

  private onDocumentPointerDown = (event: PointerEvent): void => {
    const target = event.target as HTMLElement;
    if (this.overlayEl?.nativeElement?.contains(target)) return;
    this.close.emit();
  };
}
