// packages/vue/src/components/GridBody.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type {
  GridCore,
  ColumnDefinition,
  CellPosition,
  CellRange,
  CellValue,
  DragState,
  SlotData,
  FillHandlePosition,
  VisibleColumnInfo,
  ColumnLayout,
  ColumnLayoutItem,
} from "@gp-grid/core";
import {
  isCellSelected,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  buildCellClasses,
} from "@gp-grid/core";
import { renderCell } from "../renderers/cellRenderer";
import { renderEditCell } from "../renderers/editRenderer";
import type { Row, VueCellRenderer, VueEditRenderer } from "../types";

const props = defineProps<{
  rowHeight: number;
  totalHeaderHeight: number;
  contentWidth: number;
  contentHeight: number;
  totalWidth: number;
  scrollLeft: number;
  viewportWidth: number;
  rowsWrapperOffset: number;
  activeCell: CellPosition | null;
  selectionRange: CellRange | null;
  editingCell: { row: number; col: number; initialValue: CellValue } | null;
  hoverPosition: CellPosition | null;
  error: string | null;
  isLoading: boolean;
  totalRows: number;
  slotsArray: SlotData[];
  visibleColumnsWithIndices: VisibleColumnInfo[];
  columnLayout: ColumnLayout;
  columnPositions: number[];
  columnWidths: number[];
  fillHandlePosition: FillHandlePosition | null;
  dragState: DragState;
  onScroll: () => void;
  onWheel: (e: WheelEvent, dampening: number) => void;
  wheelDampening: number;
  onCellMouseDown: (rowIndex: number, colIndex: number, e: PointerEvent) => void;
  onCellDoubleClick: (rowIndex: number, colIndex: number) => void;
  onCellMouseEnter: (rowIndex: number, colIndex: number) => void;
  onCellMouseLeave: () => void;
  onFillHandleMouseDown: (e: PointerEvent) => void;
  coreRef: GridCore<Row> | null;
  cellRenderers: Record<string, VueCellRenderer>;
  editRenderers: Record<string, VueEditRenderer>;
  globalCellRenderer?: VueCellRenderer;
  globalEditRenderer?: VueEditRenderer;
}>();

const bodyRef = ref<HTMLDivElement | null>(null);
const renderedWidth = computed(() =>
  Math.max(props.contentWidth, props.totalWidth, props.columnLayout.totalWidth),
);

// Get row classes including highlight classes
const getRowClasses = (slot: { rowIndex: number; rowData: Row }): string => {
  const highlightRowClasses =
    props.coreRef?.highlight?.computeRowClasses(slot.rowIndex, slot.rowData) ?? [];
  return ["gp-grid-row", ...highlightRowClasses].filter(Boolean).join(" ");
};

// Get cell classes
const getCellClasses = (
  rowIndex: number,
  colIndex: number,
  column: ColumnDefinition,
  rowData: Row,
  _hoverPosition: CellPosition | null,
): string => {
  const isEditing = isCellEditing(rowIndex, colIndex, props.editingCell);
  const active = isCellActive(rowIndex, colIndex, props.activeCell);
  const selected = isCellSelected(rowIndex, colIndex, props.selectionRange);
  const inFillPreview = isCellInFillPreview(
    rowIndex,
    colIndex,
    props.dragState.dragType === "fill",
    props.dragState.fillSourceRange,
    props.dragState.fillTarget,
  );
  const baseCellClasses = buildCellClasses(active, selected, isEditing, inFillPreview);

  const highlightCellClasses =
    props.coreRef?.highlight?.computeCombinedCellClasses(rowIndex, colIndex, column, rowData) ?? [];

  const isRowDragHandle = column.rowDrag === true;

  return [
    baseCellClasses,
    ...highlightCellClasses,
    isRowDragHandle ? "gp-grid-cell--row-drag-handle" : "",
  ].filter(Boolean).join(" ");
};

const getCellStyle = (item: ColumnLayoutItem): Record<string, string | number> => {
  if (item.region === "left") {
    return {
      position: "absolute",
      left: `calc(var(--gp-grid-scroll-left, 0px) + ${item.left}px)`,
      top: 0,
      width: `${item.width}px`,
      height: `${props.rowHeight}px`,
      zIndex: 6,
    };
  }
  if (item.region === "right") {
    return {
      position: "absolute",
      left: `calc(var(--gp-grid-scroll-left, 0px) + var(--gp-grid-viewport-width, 0px) - ${props.columnLayout.rightPinnedWidth - item.left}px)`,
      top: 0,
      width: `${item.width}px`,
      height: `${props.rowHeight}px`,
      zIndex: 6,
    };
  }
  return {
    position: "absolute",
    left: `${props.columnLayout.leftPinnedWidth + item.left}px`,
    top: 0,
    width: `${item.width}px`,
    height: `${props.rowHeight}px`,
  };
};

const groupLabel = (slot: SlotData): string => {
  const expanded = slot.groupExpanded === true ? "[-]" : "[+]";
  return `${expanded} ${slot.groupField ?? "Group"}: ${String(slot.groupValue ?? "")} (${slot.groupChildCount ?? 0})`;
};

defineExpose({ bodyRef });
</script>

<template>
  <div
    ref="bodyRef"
    style="flex: 1; overflow: auto; position: relative"
    @scroll="props.onScroll"
    @wheel="(e) => props.onWheel(e, props.wheelDampening)"
  >
    <!-- Content sizer - provides scroll range -->
    <div
      :style="{
        width: `${renderedWidth}px`,
        height: `${Math.max(props.contentHeight - props.totalHeaderHeight, 0)}px`,
        position: 'relative',
        minWidth: '100%',
      }"
    >
      <!-- Rows wrapper -->
      <div
        class="gp-grid-rows-wrapper"
        :style="{
          width: `${renderedWidth}px`,
          transform: `translateY(${props.rowsWrapperOffset}px)`,
        }"
      >
        <!-- Row slots -->
        <div
          v-for="slot in props.slotsArray.filter((s) => s.rowIndex >= 0)"
          :key="slot.slotId"
          :class="slot.rowKind === 'group' ? 'gp-grid-row gp-grid-row--group' : getRowClasses(slot)"
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            transform: `translateY(${slot.translateY}px)`,
            width: `${renderedWidth}px`,
            height: `${props.rowHeight}px`,
          }"
        >
          <div
            v-if="slot.rowKind === 'group'"
            class="gp-grid-row-group-cell"
            :style="{
              left: 0,
              width: `${renderedWidth}px`,
              height: `${props.rowHeight}px`,
              paddingLeft: `${12 + (slot.groupDepth ?? 0) * 16}px`,
            }"
            @pointerdown.prevent="() => slot.groupKey && props.coreRef?.toggleRowGroup(slot.groupKey)"
          >
            {{ groupLabel(slot) }}
          </div>
          <div
            v-for="item in slot.rowKind === 'group' ? [] : props.columnLayout.items"
            :key="`${slot.slotId}-${item.key}`"
            :class="[
              getCellClasses(slot.rowIndex, item.originalIndex, item.column, slot.rowData, props.hoverPosition),
              item.region !== 'center' ? 'gp-grid-cell--pinned' : '',
              item.region === 'left' ? 'gp-grid-cell--pinned-left' : '',
              item.region === 'right' ? 'gp-grid-cell--pinned-right' : '',
            ].filter(Boolean).join(' ')"
            :style="getCellStyle(item)"
            @pointerdown="(e) => props.onCellMouseDown(slot.rowIndex, item.originalIndex, e)"
            @dblclick="() => props.onCellDoubleClick(slot.rowIndex, item.originalIndex)"
            @mouseenter="() => props.onCellMouseEnter(slot.rowIndex, item.originalIndex)"
            @mouseleave="props.onCellMouseLeave"
          >
            <!-- Edit mode -->
            <template v-if="isCellEditing(slot.rowIndex, item.originalIndex, props.editingCell) && props.editingCell">
              <component
                :is="renderEditCell({
                  column: item.column,
                  rowData: slot.rowData,
                  rowIndex: slot.rowIndex,
                  colIndex: item.originalIndex,
                  initialValue: props.editingCell.initialValue,
                  core: props.coreRef,
                  editRenderers: props.editRenderers,
                  globalEditRenderer: props.globalEditRenderer,
                })"
              />
            </template>
            <!-- View mode -->
            <template v-else>
              <component
                :is="renderCell({
                  column: item.column,
                  rowData: slot.rowData,
                  rowIndex: slot.rowIndex,
                  colIndex: item.originalIndex,
                  isActive: isCellActive(slot.rowIndex, item.originalIndex, props.activeCell),
                  isSelected: isCellSelected(slot.rowIndex, item.originalIndex, props.selectionRange),
                  isEditing: false,
                  cellRenderers: props.cellRenderers,
                  globalCellRenderer: props.globalCellRenderer,
                })"
              />
            </template>
          </div>
        </div>

        <!-- Fill handle -->
        <div
          v-if="props.fillHandlePosition && !props.editingCell"
          class="gp-grid-fill-handle"
          :style="{
            top: `${props.fillHandlePosition.top}px`,
            left: `${props.fillHandlePosition.left}px`,
          }"
          @pointerdown="props.onFillHandleMouseDown"
        />

        <!-- Row drop indicator -->
        <div
          v-if="props.dragState.dragType === 'row-drag' && props.dragState.rowDrag?.dropTargetIndex !== null"
          class="gp-grid-row-drop-indicator"
          :style="{
            transform: `translateY(${props.dragState.rowDrag!.dropIndicatorY}px)`,
            width: `${renderedWidth}px`,
          }"
        />
      </div>

    </div>

    <!-- Error message -->
    <div v-if="props.error" class="gp-grid-error">
      Error: {{ props.error }}
    </div>

    <!-- Empty state -->
    <div
      v-if="!props.isLoading && !props.error && props.totalRows === 0"
      class="gp-grid-empty"
    >
      No data to display
    </div>
  </div>
</template>

// packages/angular/src/lib/components/grid-body.component.ts
import { ChangeDetectionStrategy, Component, computed, ElementRef, input, output, TemplateRef, ViewChild } from "@angular/core";
import { NgStyle, NgTemplateOutlet } from "@angular/common";
import {
  formatCellValue,
  getFieldValue,
  buildCellClasses,
  isCellActive,
  isCellEditing,
  isCellInFillPreview,
  isCellSelected,
  SlotData,
  VisibleColumnInfo,
  CellPosition,
  CellRange,
  CellValue,
  ColumnDefinition,
  ColumnLayout,
  ColumnLayoutItem,
  CellRendererParams,
  EditRendererParams,
  FillHandlePosition,
  DragState,
} from "@gp-grid/core";
import { GRID_BODY_TEMPLATE } from "./grid-body.template";

export type RowClassFn = (rowIndex: number, rowData: unknown) => string[];
export type CellClassFn = (
  rowIndex: number,
  colIndex: number,
  column: ColumnDefinition,
  rowData: unknown,
) => string[];

export type CellRendererTemplate = TemplateRef<{ $implicit: CellRendererParams }>;
export type EditRendererTemplate = TemplateRef<{ $implicit: EditRendererParams }>;

export interface FillHandlePointerDownEvent {
  event: PointerEvent;
}

export interface CellPointerDownEvent {
  rowIndex: number;
  colIndex: number;
  event: PointerEvent;
}

export interface CellPointerEnterEvent {
  rowIndex: number;
  colIndex: number;
}

export interface CellDoubleClickEvent {
  rowIndex: number;
  colIndex: number;
}

export interface EditingCellState {
  row: number;
  col: number;
  initialValue: CellValue;
}

@Component({
  selector: "gp-grid-body",
  standalone: true,
  imports: [NgStyle, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`:host { display: flex; flex: 1; min-height: 0; overflow: hidden; }`],
  template: GRID_BODY_TEMPLATE,
})
export class GridBodyComponent {
  @ViewChild("scrollContainer") scrollContainer!: ElementRef<HTMLDivElement>;
  rowHeight = input.required<number>();
  totalHeaderHeight = input.required<number>();
  contentWidth = input.required<number>();
  contentHeight = input.required<number>();
  scrollLeft = input.required<number>();
  viewportWidth = input.required<number>();
  rowsWrapperOffset = input.required<number>();
  slotsArray = input.required<SlotData[]>();
  visibleColumnWithIndices = input.required<VisibleColumnInfo[]>();
  columnLayout = input.required<ColumnLayout>();
  totalWidth = input.required<number>();
  columnPositions = input.required<number[]>();
  columnWidths = input.required<number[]>();
  totalRows = input.required<number>();
  activeCell = input<CellPosition | null>(null);
  selectionRange = input<CellRange | null>(null);
  editingCell = input<EditingCellState | null>(null);
  cellRenderers = input<Record<string, CellRendererTemplate>>({});
  globalCellRenderer = input<CellRendererTemplate | null>(null);
  editRenderers = input<Record<string, EditRendererTemplate>>({});
  globalEditRenderer = input<EditRendererTemplate | null>(null);
  hoverPosition = input<CellPosition | null>(null);
  computeRowClasses = input<RowClassFn | null>(null);
  computeCellClasses = input<CellClassFn | null>(null);
  fillHandlePosition = input<FillHandlePosition | null>(null);
  dragState = input<DragState | null>(null);

  scrolled = output<number>();
  cellPointerDown = output<CellPointerDownEvent>();
  cellPointerEnter = output<CellPointerEnterEvent>();
  cellPointerLeave = output<void>();
  cellDoubleClick = output<CellDoubleClickEvent>();
  editValueChange = output<string>();
  editCommit = output<void>();
  editCancel = output<void>();
  fillHandlePointerDown = output<FillHandlePointerDownEvent>();
  rowGroupToggle = output<string>();

  protected innerWidth = computed(() =>
    Math.max(this.contentWidth(), this.totalWidth(), this.columnLayout().totalWidth),
  );

  protected sizerHeight = computed(() =>
    Math.max(this.contentHeight() - this.totalHeaderHeight(), 0),
  );

  protected rowDropIndicator = computed(() => {
    const ds = this.dragState();
    if (ds?.dragType !== 'row-drag') return null;
    if (ds.rowDrag === null || ds.rowDrag.dropTargetIndex === null) return null;
    return ds.rowDrag;
  });

  protected rowDropIndicatorWidth = computed(() =>
    this.innerWidth(),
  );

  protected cellStyle(item: ColumnLayoutItem): Record<string, string | number> {
    if (item.region === 'left') {
      return {
        position: 'absolute',
        left: `calc(var(--gp-grid-scroll-left, 0px) + ${item.left}px)`,
        top: 0,
        width: `${item.width}px`,
        height: `${this.rowHeight()}px`,
        zIndex: 6,
      };
    }
    if (item.region === 'right') {
      return {
        position: 'absolute',
        left: `calc(var(--gp-grid-scroll-left, 0px) + var(--gp-grid-viewport-width, 0px) - ${this.columnLayout().rightPinnedWidth - item.left}px)`,
        top: 0,
        width: `${item.width}px`,
        height: `${this.rowHeight()}px`,
        zIndex: 6,
      };
    }
    return {
      position: 'absolute',
      left: `${this.columnLayout().leftPinnedWidth + item.left}px`,
      top: 0,
      width: `${item.width}px`,
      height: `${this.rowHeight()}px`,
    };
  }

  protected groupLabel(slot: SlotData): string {
    const expanded = slot.groupExpanded === true ? '[-]' : '[+]';
    return `${expanded} ${slot.groupField ?? 'Group'}: ${String(slot.groupValue ?? '')} (${slot.groupChildCount ?? 0})`;
  }

  protected cellClassWithPinning(
    slot: SlotData,
    item: ColumnLayoutItem,
  ): string {
    const classes = [
      this.cellClass(slot.rowIndex, item.originalIndex, item.column, slot.rowData),
      item.region !== 'center' ? 'gp-grid-cell--pinned' : '',
      item.region === 'left' ? 'gp-grid-cell--pinned-left' : '',
      item.region === 'right' ? 'gp-grid-cell--pinned-right' : '',
    ];
    return classes.filter(Boolean).join(' ');
  }

  protected toggleGroup(slot: SlotData): void {
    const groupKey = slot.groupKey;
    if (groupKey) {
      this.rowGroupToggle.emit(groupKey);
    }
  }

  protected wrapperTransform = computed(() =>
    `translateY(${this.rowsWrapperOffset()}px)`);

  protected onScroll(): void {
    const el = this.scrollContainer.nativeElement;
    this.scrolled.emit(el.scrollLeft);
  }

  protected cellParams(
    rowData: unknown,
    column: ColumnDefinition,
    rowIndex: number,
    colIndex: number,
  ): CellRendererParams {
    const rawValue = getFieldValue(rowData, column.field);
    const displayValue = column.valueFormatter
      ? column.valueFormatter(rawValue)
      : rawValue;
    return {
      value: displayValue,
      rowData,
      column,
      rowIndex,
      colIndex,
      isActive: isCellActive(rowIndex, colIndex, this.activeCell()),
      isSelected: isCellSelected(rowIndex, colIndex, this.selectionRange()),
      isEditing: false,
    };
  }

  protected cellTemplate(column: ColumnDefinition): CellRendererTemplate | null {
    const renderer: unknown = column.cellRenderer;
    if (renderer instanceof TemplateRef) {
      return renderer as CellRendererTemplate;
    }
    if (typeof renderer === 'string') {
      const registered = this.cellRenderers()[renderer];
      if (registered) return registered;
    }
    return this.globalCellRenderer();
  }

  protected editTemplate(column: ColumnDefinition): EditRendererTemplate | null {
    const renderer: unknown = (column as { editRenderer?: unknown }).editRenderer;
    if (renderer instanceof TemplateRef) {
      return renderer as EditRendererTemplate;
    }
    if (typeof renderer === 'string') {
      const registered = this.editRenderers()[renderer];
      if (registered) return registered;
    }
    return this.globalEditRenderer();
  }

  protected editParams(
    rowData: unknown,
    column: ColumnDefinition,
    rowIndex: number,
    colIndex: number,
  ): EditRendererParams {
    const ec = this.editingCell();
    const rawValue = getFieldValue(rowData, column.field);
    const displayValue = column.valueFormatter
      ? column.valueFormatter(rawValue)
      : rawValue;
    return {
      value: displayValue,
      rowData,
      column,
      rowIndex,
      colIndex,
      isActive: true,
      isSelected: true,
      isEditing: true,
      initialValue: ec?.initialValue ?? null,
      onValueChange: (newValue) => {
        const s = newValue === null || newValue === undefined ? '' : String(newValue);
        this.editValueChange.emit(s);
      },
      onCommit: () => this.editCommit.emit(),
      onCancel: () => this.editCancel.emit(),
    };
  }

  protected cellDisplay(
    rowData: unknown,
    column: ColumnDefinition,
    rowIndex: number,
    colIndex: number,
  ): string {
    const renderer = column.cellRenderer;
    const value = getFieldValue(rowData, column.field);
    if (typeof renderer === 'function') {
      const params = this.cellParams(rowData, column, rowIndex, colIndex);
      const result = renderer(params);
      return result === null || result === undefined ? '' : String(result);
    }
    return formatCellValue(value, column.valueFormatter);
  }

  protected cellClass(
    rowIndex: number,
    colIndex: number,
    column: ColumnDefinition,
    rowData: unknown,
  ): string {
    const editingCell = this.editingCell();
    // Read hoverPosition to register this signal as a dep so Angular re-renders on hover change.
    this.hoverPosition();
    const ds = this.dragState();
    const inFillPreview = isCellInFillPreview(
      rowIndex,
      colIndex,
      ds?.dragType === "fill",
      ds?.fillSourceRange ?? null,
      ds?.fillTarget ?? null,
    );
    const base = buildCellClasses(
      isCellActive(rowIndex, colIndex, this.activeCell()),
      isCellSelected(rowIndex, colIndex, this.selectionRange()),
      isCellEditing(rowIndex, colIndex, editingCell),
      inFillPreview,
    );
    const withHandle = column.rowDrag === true
      ? `${base} gp-grid-cell--row-drag-handle`
      : base;
    const fn = this.computeCellClasses();
    if (fn === null) return withHandle;
    const extra = fn(rowIndex, colIndex, column, rowData);
    if (extra.length === 0) return withHandle;
    return `${withHandle} ${extra.join(' ')}`;
  }

  protected rowClass(rowIndex: number, rowData: unknown): string {
    this.hoverPosition();
    const fn = this.computeRowClasses();
    if (fn === null) return 'gp-grid-row';
    const extra = fn(rowIndex, rowData);
    if (extra.length === 0) return 'gp-grid-row';
    return `gp-grid-row ${extra.join(' ')}`;
  }

  protected isEditing(rowIndex: number, colIndex: number): boolean {
    return isCellEditing(rowIndex, colIndex, this.editingCell());
  }

  protected editInitialValue(): string {
    const ec = this.editingCell();
    if (ec === null || ec.initialValue === null || ec.initialValue === undefined) return '';
    return String(ec.initialValue);
  }

  protected asInput(event: Event): HTMLInputElement {
    return event.target as HTMLInputElement;
  }

  protected onEditFocus(event: FocusEvent): void {
    (event.target as HTMLInputElement).select();
  }

  protected onEditKeyDown(event: KeyboardEvent): void {
    event.stopPropagation();
    if (event.key === 'Enter') {
      this.editCommit.emit();
    } else if (event.key === 'Escape') {
      this.editCancel.emit();
    }
  }
}
