// packages/react/src/components/ResizeHandle.tsx
// packages/react/src/components/ResizeHandle.tsx

import React from "react";
import type { ResizeTarget } from "@gp-grid/core";

/** Input routes of the edge handles, provided by `useInputHandler`. */
export interface ResizeHandleActions {
  onColumnPointerDown: (colIndex: number, width: number, e: React.PointerEvent) => void;
  onRowPointerDown: (rowIndex: number, height: number, e: React.PointerEvent) => void;
  onDoubleClick: (target: ResizeTarget) => void;
}

export interface ResizeHandleProps {
  axis: ResizeTarget["axis"];
  /** Layout index of a column, or view index of a row. */
  index: number;
  /** Displayed width or height a drag starts from, in px. */
  size: number;
  /** The handle's target is being dragged. */
  active?: boolean;
  actions: ResizeHandleActions;
}

const AXIS_CLASS = {
  column: "gp-grid-header-resize-handle",
  row: "gp-grid-row-resize-handle",
} as const;

const toTarget = (axis: ResizeTarget["axis"], index: number): ResizeTarget =>
  axis === "column" ? { axis, colIndex: index } : { axis, rowIndex: index };

/**
 * Pointer-only edge target: a drag resizes, a double-click fits, and neither
 * reaches the cell underneath. The grid keys are its keyboard equivalent.
 */
export const ResizeHandle = (props: ResizeHandleProps): React.ReactNode => {
  const { axis, index, size, active = false, actions } = props;
  const className = AXIS_CLASS[axis];

  const handlePointerDown = (e: React.PointerEvent): void => {
    e.stopPropagation();
    if (axis === "column") actions.onColumnPointerDown(index, size, e);
    else actions.onRowPointerDown(index, size, e);
  };

  const handleDoubleClick = (e: React.MouseEvent): void => {
    e.stopPropagation();
    actions.onDoubleClick(toTarget(axis, index));
  };

  return (
    <div
      className={active ? `${className} ${className}--active` : className}
      aria-hidden="true"
      onPointerDown={handlePointerDown}
      onDoubleClick={handleDoubleClick}
    />
  );
};

// packages/angular/src/lib/components/resize-handle.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import type { ResizeTarget } from '@gp-grid/core';

export type ResizeAxis = ResizeTarget['axis'];

export interface ResizeHandlePointerDownEvent {
  /** Layout index of the column, or view index of the row. */
  index: number;
  /** Displayed width or height of the target. */
  size: number;
  event: PointerEvent;
}

const HANDLE_CLASS: Record<ResizeAxis, string> = {
  column: 'gp-grid-header-resize-handle',
  row: 'gp-grid-row-resize-handle',
};

/**
 * Pointer-only edge target: a drag resizes, a double-click fits, and neither
 * reaches the cell underneath. The grid keys are its keyboard equivalent.
 */
@Component({
  selector: 'div[gpGridResizeHandle]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
  host: {
    'aria-hidden': 'true',
    '[class]': 'hostClass()',
    '(pointerdown)': 'onPointerDown($event)',
    '(dblclick)': 'onDoubleClick($event)',
  },
})
export class ResizeHandleComponent {
  axis = input.required<ResizeAxis>();
  index = input.required<number>();
  size = input.required<number>();
  /** Whether this handle's target is being dragged. */
  resizing = input<boolean>(false);

  resizePointerDown = output<ResizeHandlePointerDownEvent>();
  resizeDoubleClick = output<ResizeTarget>();

  protected hostClass = computed(() => {
    const base = HANDLE_CLASS[this.axis()];
    return this.resizing() ? `${base} ${base}--active` : base;
  });

  private target(): ResizeTarget {
    if (this.axis() === 'row') return { axis: 'row', rowIndex: this.index() };
    return { axis: 'column', colIndex: this.index() };
  }

  protected onPointerDown(event: PointerEvent): void {
    event.stopPropagation();
    this.resizePointerDown.emit({ index: this.index(), size: this.size(), event });
  }

  protected onDoubleClick(event: MouseEvent): void {
    event.stopPropagation();
    this.resizeDoubleClick.emit(this.target());
  }
}
